// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: hexstrike.proto

package hexstrike

import (
	context "context"
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HexstrikeAdapter_Execute_FullMethodName              = "/openclaw.hexstrike.HexstrikeAdapter/Execute"
	HexstrikeAdapter_GetCapabilities_FullMethodName      = "/openclaw.hexstrike.HexstrikeAdapter/GetCapabilities"
	HexstrikeAdapter_HealthCheck_FullMethodName          = "/openclaw.hexstrike.HexstrikeAdapter/HealthCheck"
	HexstrikeAdapter_GeneratePayload_FullMethodName      = "/openclaw.hexstrike.HexstrikeAdapter/GeneratePayload"
	HexstrikeAdapter_SendPhishingEmail_FullMethodName    = "/openclaw.hexstrike.HexstrikeAdapter/SendPhishingEmail"
	HexstrikeAdapter_ExploitVulnerability_FullMethodName = "/openclaw.hexstrike.HexstrikeAdapter/ExploitVulnerability"
)

// HexstrikeAdapterClient is the client API for HexstrikeAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hexstrike Adapter Service, extends core functionality
type HexstrikeAdapterClient interface {
	Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error)
	GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error)
	HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error)
	// Hexstrike specific functions
	GeneratePayload(ctx context.Context, in *GeneratePayloadRequest, opts ...grpc.CallOption) (*GeneratePayloadResponse, error)
	SendPhishingEmail(ctx context.Context, in *PhishingRequest, opts ...grpc.CallOption) (*PhishingResponse, error)
	ExploitVulnerability(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*ExploitResponse, error)
}

type hexstrikeAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewHexstrikeAdapterClient(cc grpc.ClientConnInterface) HexstrikeAdapterClient {
	return &hexstrikeAdapterClient{cc}
}

func (c *hexstrikeAdapterClient) Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.OperationResponse)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexstrikeAdapterClient) GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.CapabilityList)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexstrikeAdapterClient) HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.HealthStatus)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexstrikeAdapterClient) GeneratePayload(ctx context.Context, in *GeneratePayloadRequest, opts ...grpc.CallOption) (*GeneratePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePayloadResponse)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_GeneratePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexstrikeAdapterClient) SendPhishingEmail(ctx context.Context, in *PhishingRequest, opts ...grpc.CallOption) (*PhishingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhishingResponse)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_SendPhishingEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexstrikeAdapterClient) ExploitVulnerability(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*ExploitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExploitResponse)
	err := c.cc.Invoke(ctx, HexstrikeAdapter_ExploitVulnerability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HexstrikeAdapterServer is the server API for HexstrikeAdapter service.
// All implementations must embed UnimplementedHexstrikeAdapterServer
// for forward compatibility.
//
// Hexstrike Adapter Service, extends core functionality
type HexstrikeAdapterServer interface {
	Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error)
	GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error)
	HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error)
	// Hexstrike specific functions
	GeneratePayload(context.Context, *GeneratePayloadRequest) (*GeneratePayloadResponse, error)
	SendPhishingEmail(context.Context, *PhishingRequest) (*PhishingResponse, error)
	ExploitVulnerability(context.Context, *ExploitRequest) (*ExploitResponse, error)
	mustEmbedUnimplementedHexstrikeAdapterServer()
}

// UnimplementedHexstrikeAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHexstrikeAdapterServer struct{}

func (UnimplementedHexstrikeAdapterServer) Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedHexstrikeAdapterServer) GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedHexstrikeAdapterServer) HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHexstrikeAdapterServer) GeneratePayload(context.Context, *GeneratePayloadRequest) (*GeneratePayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePayload not implemented")
}
func (UnimplementedHexstrikeAdapterServer) SendPhishingEmail(context.Context, *PhishingRequest) (*PhishingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPhishingEmail not implemented")
}
func (UnimplementedHexstrikeAdapterServer) ExploitVulnerability(context.Context, *ExploitRequest) (*ExploitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExploitVulnerability not implemented")
}
func (UnimplementedHexstrikeAdapterServer) mustEmbedUnimplementedHexstrikeAdapterServer() {}
func (UnimplementedHexstrikeAdapterServer) testEmbeddedByValue()                          {}

// UnsafeHexstrikeAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HexstrikeAdapterServer will
// result in compilation errors.
type UnsafeHexstrikeAdapterServer interface {
	mustEmbedUnimplementedHexstrikeAdapterServer()
}

func RegisterHexstrikeAdapterServer(s grpc.ServiceRegistrar, srv HexstrikeAdapterServer) {
	// If the following call panics, it indicates UnimplementedHexstrikeAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HexstrikeAdapter_ServiceDesc, srv)
}

func _HexstrikeAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).Execute(ctx, req.(*core.OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexstrikeAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).GetCapabilities(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexstrikeAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).HealthCheck(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexstrikeAdapter_GeneratePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).GeneratePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_GeneratePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).GeneratePayload(ctx, req.(*GeneratePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexstrikeAdapter_SendPhishingEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhishingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).SendPhishingEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_SendPhishingEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).SendPhishingEmail(ctx, req.(*PhishingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexstrikeAdapter_ExploitVulnerability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexstrikeAdapterServer).ExploitVulnerability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HexstrikeAdapter_ExploitVulnerability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexstrikeAdapterServer).ExploitVulnerability(ctx, req.(*ExploitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HexstrikeAdapter_ServiceDesc is the grpc.ServiceDesc for HexstrikeAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HexstrikeAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.hexstrike.HexstrikeAdapter",
	HandlerType: (*HexstrikeAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _HexstrikeAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _HexstrikeAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _HexstrikeAdapter_HealthCheck_Handler,
		},
		{
			MethodName: "GeneratePayload",
			Handler:    _HexstrikeAdapter_GeneratePayload_Handler,
		},
		{
			MethodName: "SendPhishingEmail",
			Handler:    _HexstrikeAdapter_SendPhishingEmail_Handler,
		},
		{
			MethodName: "ExploitVulnerability",
			Handler:    _HexstrikeAdapter_ExploitVulnerability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hexstrike.proto",
}
