// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hexstrike.proto

package hexstrike

import (
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hexstrike specific messages
type GeneratePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g., "hta", "exe", "dll", "ps1", "macro"
	Lhost         string                 `protobuf:"bytes,2,opt,name=lhost,proto3" json:"lhost,omitempty"`
	Lport         string                 `protobuf:"bytes,3,opt,name=lport,proto3" json:"lport,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayloadRequest) Reset() {
	*x = GeneratePayloadRequest{}
	mi := &file_hexstrike_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayloadRequest) ProtoMessage() {}

func (x *GeneratePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayloadRequest.ProtoReflect.Descriptor instead.
func (*GeneratePayloadRequest) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePayloadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneratePayloadRequest) GetLhost() string {
	if x != nil {
		return x.Lhost
	}
	return ""
}

func (x *GeneratePayloadRequest) GetLport() string {
	if x != nil {
		return x.Lport
	}
	return ""
}

func (x *GeneratePayloadRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GeneratePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadPath   string                 `protobuf:"bytes,1,opt,name=payload_path,json=payloadPath,proto3" json:"payload_path,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayloadResponse) Reset() {
	*x = GeneratePayloadResponse{}
	mi := &file_hexstrike_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayloadResponse) ProtoMessage() {}

func (x *GeneratePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayloadResponse.ProtoReflect.Descriptor instead.
func (*GeneratePayloadResponse) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePayloadResponse) GetPayloadPath() string {
	if x != nil {
		return x.PayloadPath
	}
	return ""
}

func (x *GeneratePayloadResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *GeneratePayloadResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PhishingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TemplateName   string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Subject        string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	AttachmentPath string                 `protobuf:"bytes,3,opt,name=attachment_path,json=attachmentPath,proto3" json:"attachment_path,omitempty"`
	Recipients     []string               `protobuf:"bytes,4,rep,name=recipients,proto3" json:"recipients,omitempty"`
	SmtpConfig     map[string]string      `protobuf:"bytes,5,rep,name=smtp_config,json=smtpConfig,proto3" json:"smtp_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhishingRequest) Reset() {
	*x = PhishingRequest{}
	mi := &file_hexstrike_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhishingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhishingRequest) ProtoMessage() {}

func (x *PhishingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhishingRequest.ProtoReflect.Descriptor instead.
func (*PhishingRequest) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{2}
}

func (x *PhishingRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *PhishingRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PhishingRequest) GetAttachmentPath() string {
	if x != nil {
		return x.AttachmentPath
	}
	return ""
}

func (x *PhishingRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *PhishingRequest) GetSmtpConfig() map[string]string {
	if x != nil {
		return x.SmtpConfig
	}
	return nil
}

type PhishingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SentCount        int32                  `protobuf:"varint,1,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	FailedRecipients []string               `protobuf:"bytes,2,rep,name=failed_recipients,json=failedRecipients,proto3" json:"failed_recipients,omitempty"`
	MessageId        string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhishingResponse) Reset() {
	*x = PhishingResponse{}
	mi := &file_hexstrike_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhishingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhishingResponse) ProtoMessage() {}

func (x *PhishingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhishingResponse.ProtoReflect.Descriptor instead.
func (*PhishingResponse) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{3}
}

func (x *PhishingResponse) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *PhishingResponse) GetFailedRecipients() []string {
	if x != nil {
		return x.FailedRecipients
	}
	return nil
}

func (x *PhishingResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ExploitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Vulnerability string                 `protobuf:"bytes,2,opt,name=vulnerability,proto3" json:"vulnerability,omitempty"` // CVE number or name
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploitRequest) Reset() {
	*x = ExploitRequest{}
	mi := &file_hexstrike_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitRequest) ProtoMessage() {}

func (x *ExploitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitRequest.ProtoReflect.Descriptor instead.
func (*ExploitRequest) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{4}
}

func (x *ExploitRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExploitRequest) GetVulnerability() string {
	if x != nil {
		return x.Vulnerability
	}
	return ""
}

func (x *ExploitRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ExploitRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExploitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploitResponse) Reset() {
	*x = ExploitResponse{}
	mi := &file_hexstrike_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitResponse) ProtoMessage() {}

func (x *ExploitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hexstrike_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitResponse.ProtoReflect.Descriptor instead.
func (*ExploitResponse) Descriptor() ([]byte, []int) {
	return file_hexstrike_proto_rawDescGZIP(), []int{5}
}

func (x *ExploitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExploitResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExploitResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_hexstrike_proto protoreflect.FileDescriptor

const file_hexstrike_proto_rawDesc = "" +
	"\n" +
	"\x0fhexstrike.proto\x12\x12openclaw.hexstrike\x1a\n" +
	"core.proto\"\xe7\x01\n" +
	"\x16GeneratePayloadRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05lhost\x18\x02 \x01(\tR\x05lhost\x12\x14\n" +
	"\x05lport\x18\x03 \x01(\tR\x05lport\x12Q\n" +
	"\aoptions\x18\x04 \x03(\v27.openclaw.hexstrike.GeneratePayloadRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x17GeneratePayloadResponse\x12!\n" +
	"\fpayload_path\x18\x01 \x01(\tR\vpayloadPath\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xae\x02\n" +
	"\x0fPhishingRequest\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12'\n" +
	"\x0fattachment_path\x18\x03 \x01(\tR\x0eattachmentPath\x12\x1e\n" +
	"\n" +
	"recipients\x18\x04 \x03(\tR\n" +
	"recipients\x12T\n" +
	"\vsmtp_config\x18\x05 \x03(\v23.openclaw.hexstrike.PhishingRequest.SmtpConfigEntryR\n" +
	"smtpConfig\x1a=\n" +
	"\x0fSmtpConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x10PhishingResponse\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x01 \x01(\x05R\tsentCount\x12+\n" +
	"\x11failed_recipients\x18\x02 \x03(\tR\x10failedRecipients\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\xef\x01\n" +
	"\x0eExploitRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12$\n" +
	"\rvulnerability\x18\x02 \x01(\tR\rvulnerability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12I\n" +
	"\aoptions\x18\x04 \x03(\v2/.openclaw.hexstrike.ExploitRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x0fExploitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId2\x97\x04\n" +
	"\x10HexstrikeAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatus\x12j\n" +
	"\x0fGeneratePayload\x12*.openclaw.hexstrike.GeneratePayloadRequest\x1a+.openclaw.hexstrike.GeneratePayloadResponse\x12^\n" +
	"\x11SendPhishingEmail\x12#.openclaw.hexstrike.PhishingRequest\x1a$.openclaw.hexstrike.PhishingResponse\x12_\n" +
	"\x14ExploitVulnerability\x12\".openclaw.hexstrike.ExploitRequest\x1a#.openclaw.hexstrike.ExploitResponseB?Z=github.com/OpenClaw-Security/Stealth-Core/pkg/proto/hexstrikeb\x06proto3"

var (
	file_hexstrike_proto_rawDescOnce sync.Once
	file_hexstrike_proto_rawDescData []byte
)

func file_hexstrike_proto_rawDescGZIP() []byte {
	file_hexstrike_proto_rawDescOnce.Do(func() {
		file_hexstrike_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hexstrike_proto_rawDesc), len(file_hexstrike_proto_rawDesc)))
	})
	return file_hexstrike_proto_rawDescData
}

var file_hexstrike_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_hexstrike_proto_goTypes = []any{
	(*GeneratePayloadRequest)(nil),  // 0: openclaw.hexstrike.GeneratePayloadRequest
	(*GeneratePayloadResponse)(nil), // 1: openclaw.hexstrike.GeneratePayloadResponse
	(*PhishingRequest)(nil),         // 2: openclaw.hexstrike.PhishingRequest
	(*PhishingResponse)(nil),        // 3: openclaw.hexstrike.PhishingResponse
	(*ExploitRequest)(nil),          // 4: openclaw.hexstrike.ExploitRequest
	(*ExploitResponse)(nil),         // 5: openclaw.hexstrike.ExploitResponse
	nil,                             // 6: openclaw.hexstrike.GeneratePayloadRequest.OptionsEntry
	nil,                             // 7: openclaw.hexstrike.PhishingRequest.SmtpConfigEntry
	nil,                             // 8: openclaw.hexstrike.ExploitRequest.OptionsEntry
	(*core.OperationRequest)(nil),   // 9: openclaw.core.OperationRequest
	(*core.Empty)(nil),              // 10: openclaw.core.Empty
	(*core.OperationResponse)(nil),  // 11: openclaw.core.OperationResponse
	(*core.CapabilityList)(nil),     // 12: openclaw.core.CapabilityList
	(*core.HealthStatus)(nil),       // 13: openclaw.core.HealthStatus
}
var file_hexstrike_proto_depIdxs = []int32{
	6,  // 0: openclaw.hexstrike.GeneratePayloadRequest.options:type_name -> openclaw.hexstrike.GeneratePayloadRequest.OptionsEntry
	7,  // 1: openclaw.hexstrike.PhishingRequest.smtp_config:type_name -> openclaw.hexstrike.PhishingRequest.SmtpConfigEntry
	8,  // 2: openclaw.hexstrike.ExploitRequest.options:type_name -> openclaw.hexstrike.ExploitRequest.OptionsEntry
	9,  // 3: openclaw.hexstrike.HexstrikeAdapter.Execute:input_type -> openclaw.core.OperationRequest
	10, // 4: openclaw.hexstrike.HexstrikeAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	10, // 5: openclaw.hexstrike.HexstrikeAdapter.HealthCheck:input_type -> openclaw.core.Empty
	0,  // 6: openclaw.hexstrike.HexstrikeAdapter.GeneratePayload:input_type -> openclaw.hexstrike.GeneratePayloadRequest
	2,  // 7: openclaw.hexstrike.HexstrikeAdapter.SendPhishingEmail:input_type -> openclaw.hexstrike.PhishingRequest
	4,  // 8: openclaw.hexstrike.HexstrikeAdapter.ExploitVulnerability:input_type -> openclaw.hexstrike.ExploitRequest
	11, // 9: openclaw.hexstrike.HexstrikeAdapter.Execute:output_type -> openclaw.core.OperationResponse
	12, // 10: openclaw.hexstrike.HexstrikeAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	13, // 11: openclaw.hexstrike.HexstrikeAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	1,  // 12: openclaw.hexstrike.HexstrikeAdapter.GeneratePayload:output_type -> openclaw.hexstrike.GeneratePayloadResponse
	3,  // 13: openclaw.hexstrike.HexstrikeAdapter.SendPhishingEmail:output_type -> openclaw.hexstrike.PhishingResponse
	5,  // 14: openclaw.hexstrike.HexstrikeAdapter.ExploitVulnerability:output_type -> openclaw.hexstrike.ExploitResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_hexstrike_proto_init() }
func file_hexstrike_proto_init() {
	if File_hexstrike_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hexstrike_proto_rawDesc), len(file_hexstrike_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hexstrike_proto_goTypes,
		DependencyIndexes: file_hexstrike_proto_depIdxs,
		MessageInfos:      file_hexstrike_proto_msgTypes,
	}.Build()
	File_hexstrike_proto = out.File
	file_hexstrike_proto_goTypes = nil
	file_hexstrike_proto_depIdxs = nil
}
