// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: thesilencer.proto

package thesilencer

import (
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TheSilencer specific messages
type ObfuscateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	Technique     string                 `protobuf:"bytes,2,opt,name=technique,proto3" json:"technique,omitempty"` // polymorphic, metamorphic, encryption, etc.
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObfuscateRequest) Reset() {
	*x = ObfuscateRequest{}
	mi := &file_thesilencer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObfuscateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObfuscateRequest) ProtoMessage() {}

func (x *ObfuscateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObfuscateRequest.ProtoReflect.Descriptor instead.
func (*ObfuscateRequest) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{0}
}

func (x *ObfuscateRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *ObfuscateRequest) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *ObfuscateRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ObfuscateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OutputPath         string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	OriginalChecksum   string                 `protobuf:"bytes,2,opt,name=original_checksum,json=originalChecksum,proto3" json:"original_checksum,omitempty"`
	ObfuscatedChecksum string                 `protobuf:"bytes,3,opt,name=obfuscated_checksum,json=obfuscatedChecksum,proto3" json:"obfuscated_checksum,omitempty"`
	ReductionRate      int32                  `protobuf:"varint,4,opt,name=reduction_rate,json=reductionRate,proto3" json:"reduction_rate,omitempty"` // detection rate reduction percentage
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ObfuscateResponse) Reset() {
	*x = ObfuscateResponse{}
	mi := &file_thesilencer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObfuscateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObfuscateResponse) ProtoMessage() {}

func (x *ObfuscateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObfuscateResponse.ProtoReflect.Descriptor instead.
func (*ObfuscateResponse) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{1}
}

func (x *ObfuscateResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *ObfuscateResponse) GetOriginalChecksum() string {
	if x != nil {
		return x.OriginalChecksum
	}
	return ""
}

func (x *ObfuscateResponse) GetObfuscatedChecksum() string {
	if x != nil {
		return x.ObfuscatedChecksum
	}
	return ""
}

func (x *ObfuscateResponse) GetReductionRate() int32 {
	if x != nil {
		return x.ReductionRate
	}
	return 0
}

type DetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	AvEngines     []string               `protobuf:"bytes,2,rep,name=av_engines,json=avEngines,proto3" json:"av_engines,omitempty"` // specific AVs to test against
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionRequest) Reset() {
	*x = DetectionRequest{}
	mi := &file_thesilencer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionRequest) ProtoMessage() {}

func (x *DetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionRequest.ProtoReflect.Descriptor instead.
func (*DetectionRequest) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DetectionRequest) GetAvEngines() []string {
	if x != nil {
		return x.AvEngines
	}
	return nil
}

type DetectionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Detected       bool                   `protobuf:"varint,1,opt,name=detected,proto3" json:"detected,omitempty"`
	DetectedBy     []string               `protobuf:"bytes,2,rep,name=detected_by,json=detectedBy,proto3" json:"detected_by,omitempty"`
	DetectionNames map[string]string      `protobuf:"bytes,3,rep,name=detection_names,json=detectionNames,proto3" json:"detection_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // AV name -> detection name
	Score          int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                                                                                                                  // detection score 0-100
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_thesilencer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{3}
}

func (x *DetectionResponse) GetDetected() bool {
	if x != nil {
		return x.Detected
	}
	return false
}

func (x *DetectionResponse) GetDetectedBy() []string {
	if x != nil {
		return x.DetectedBy
	}
	return nil
}

func (x *DetectionResponse) GetDetectionNames() map[string]string {
	if x != nil {
		return x.DetectionNames
	}
	return nil
}

func (x *DetectionResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // secure_delete, overwrite, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_thesilencer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{4}
}

func (x *CleanupRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *CleanupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CleanedCount  int32                  `protobuf:"varint,1,opt,name=cleaned_count,json=cleanedCount,proto3" json:"cleaned_count,omitempty"`
	FailedPaths   []string               `protobuf:"bytes,2,rep,name=failed_paths,json=failedPaths,proto3" json:"failed_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_thesilencer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{5}
}

func (x *CleanupResponse) GetCleanedCount() int32 {
	if x != nil {
		return x.CleanedCount
	}
	return 0
}

func (x *CleanupResponse) GetFailedPaths() []string {
	if x != nil {
		return x.FailedPaths
	}
	return nil
}

type BypassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technique     string                 `protobuf:"bytes,1,opt,name=technique,proto3" json:"technique,omitempty"`
	TargetEdr     string                 `protobuf:"bytes,2,opt,name=target_edr,json=targetEdr,proto3" json:"target_edr,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BypassRequest) Reset() {
	*x = BypassRequest{}
	mi := &file_thesilencer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BypassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassRequest) ProtoMessage() {}

func (x *BypassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassRequest.ProtoReflect.Descriptor instead.
func (*BypassRequest) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{6}
}

func (x *BypassRequest) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *BypassRequest) GetTargetEdr() string {
	if x != nil {
		return x.TargetEdr
	}
	return ""
}

func (x *BypassRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type BypassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BypassMethod  string                 `protobuf:"bytes,2,opt,name=bypass_method,json=bypassMethod,proto3" json:"bypass_method,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BypassResponse) Reset() {
	*x = BypassResponse{}
	mi := &file_thesilencer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BypassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassResponse) ProtoMessage() {}

func (x *BypassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thesilencer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassResponse.ProtoReflect.Descriptor instead.
func (*BypassResponse) Descriptor() ([]byte, []int) {
	return file_thesilencer_proto_rawDescGZIP(), []int{7}
}

func (x *BypassResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BypassResponse) GetBypassMethod() string {
	if x != nil {
		return x.BypassMethod
	}
	return ""
}

func (x *BypassResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_thesilencer_proto protoreflect.FileDescriptor

const file_thesilencer_proto_rawDesc = "" +
	"\n" +
	"\x11thesilencer.proto\x12\x14openclaw.thesilencer\x1a\n" +
	"core.proto\"\xda\x01\n" +
	"\x10ObfuscateRequest\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x1c\n" +
	"\ttechnique\x18\x02 \x01(\tR\ttechnique\x12M\n" +
	"\aoptions\x18\x03 \x03(\v23.openclaw.thesilencer.ObfuscateRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x11ObfuscateResponse\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath\x12+\n" +
	"\x11original_checksum\x18\x02 \x01(\tR\x10originalChecksum\x12/\n" +
	"\x13obfuscated_checksum\x18\x03 \x01(\tR\x12obfuscatedChecksum\x12%\n" +
	"\x0ereduction_rate\x18\x04 \x01(\x05R\rreductionRate\"N\n" +
	"\x10DetectionRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"av_engines\x18\x02 \x03(\tR\tavEngines\"\x8f\x02\n" +
	"\x11DetectionResponse\x12\x1a\n" +
	"\bdetected\x18\x01 \x01(\bR\bdetected\x12\x1f\n" +
	"\vdetected_by\x18\x02 \x03(\tR\n" +
	"detectedBy\x12d\n" +
	"\x0fdetection_names\x18\x03 \x03(\v2;.openclaw.thesilencer.DetectionResponse.DetectionNamesEntryR\x0edetectionNames\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x1aA\n" +
	"\x13DetectionNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x0eCleanupRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"Y\n" +
	"\x0fCleanupResponse\x12#\n" +
	"\rcleaned_count\x18\x01 \x01(\x05R\fcleanedCount\x12!\n" +
	"\ffailed_paths\x18\x02 \x03(\tR\vfailedPaths\"\xd4\x01\n" +
	"\rBypassRequest\x12\x1c\n" +
	"\ttechnique\x18\x01 \x01(\tR\ttechnique\x12\x1d\n" +
	"\n" +
	"target_edr\x18\x02 \x01(\tR\ttargetEdr\x12J\n" +
	"\aoptions\x18\x03 \x03(\v20.openclaw.thesilencer.BypassRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x0eBypassResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rbypass_method\x18\x02 \x01(\tR\fbypassMethod\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails2\xe4\x04\n" +
	"\x12TheSilencerAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatus\x12`\n" +
	"\rObfuscateFile\x12&.openclaw.thesilencer.ObfuscateRequest\x1a'.openclaw.thesilencer.ObfuscateResponse\x12[\n" +
	"\bDetectAV\x12&.openclaw.thesilencer.DetectionRequest\x1a'.openclaw.thesilencer.DetectionResponse\x12Z\n" +
	"\vCleanTraces\x12$.openclaw.thesilencer.CleanupRequest\x1a%.openclaw.thesilencer.CleanupResponse\x12[\n" +
	"\x0eBypassDefender\x12#.openclaw.thesilencer.BypassRequest\x1a$.openclaw.thesilencer.BypassResponseBAZ?github.com/OpenClaw-Security/Stealth-Core/pkg/proto/thesilencerb\x06proto3"

var (
	file_thesilencer_proto_rawDescOnce sync.Once
	file_thesilencer_proto_rawDescData []byte
)

func file_thesilencer_proto_rawDescGZIP() []byte {
	file_thesilencer_proto_rawDescOnce.Do(func() {
		file_thesilencer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thesilencer_proto_rawDesc), len(file_thesilencer_proto_rawDesc)))
	})
	return file_thesilencer_proto_rawDescData
}

var file_thesilencer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_thesilencer_proto_goTypes = []any{
	(*ObfuscateRequest)(nil),       // 0: openclaw.thesilencer.ObfuscateRequest
	(*ObfuscateResponse)(nil),      // 1: openclaw.thesilencer.ObfuscateResponse
	(*DetectionRequest)(nil),       // 2: openclaw.thesilencer.DetectionRequest
	(*DetectionResponse)(nil),      // 3: openclaw.thesilencer.DetectionResponse
	(*CleanupRequest)(nil),         // 4: openclaw.thesilencer.CleanupRequest
	(*CleanupResponse)(nil),        // 5: openclaw.thesilencer.CleanupResponse
	(*BypassRequest)(nil),          // 6: openclaw.thesilencer.BypassRequest
	(*BypassResponse)(nil),         // 7: openclaw.thesilencer.BypassResponse
	nil,                            // 8: openclaw.thesilencer.ObfuscateRequest.OptionsEntry
	nil,                            // 9: openclaw.thesilencer.DetectionResponse.DetectionNamesEntry
	nil,                            // 10: openclaw.thesilencer.BypassRequest.OptionsEntry
	(*core.OperationRequest)(nil),  // 11: openclaw.core.OperationRequest
	(*core.Empty)(nil),             // 12: openclaw.core.Empty
	(*core.OperationResponse)(nil), // 13: openclaw.core.OperationResponse
	(*core.CapabilityList)(nil),    // 14: openclaw.core.CapabilityList
	(*core.HealthStatus)(nil),      // 15: openclaw.core.HealthStatus
}
var file_thesilencer_proto_depIdxs = []int32{
	8,  // 0: openclaw.thesilencer.ObfuscateRequest.options:type_name -> openclaw.thesilencer.ObfuscateRequest.OptionsEntry
	9,  // 1: openclaw.thesilencer.DetectionResponse.detection_names:type_name -> openclaw.thesilencer.DetectionResponse.DetectionNamesEntry
	10, // 2: openclaw.thesilencer.BypassRequest.options:type_name -> openclaw.thesilencer.BypassRequest.OptionsEntry
	11, // 3: openclaw.thesilencer.TheSilencerAdapter.Execute:input_type -> openclaw.core.OperationRequest
	12, // 4: openclaw.thesilencer.TheSilencerAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	12, // 5: openclaw.thesilencer.TheSilencerAdapter.HealthCheck:input_type -> openclaw.core.Empty
	0,  // 6: openclaw.thesilencer.TheSilencerAdapter.ObfuscateFile:input_type -> openclaw.thesilencer.ObfuscateRequest
	2,  // 7: openclaw.thesilencer.TheSilencerAdapter.DetectAV:input_type -> openclaw.thesilencer.DetectionRequest
	4,  // 8: openclaw.thesilencer.TheSilencerAdapter.CleanTraces:input_type -> openclaw.thesilencer.CleanupRequest
	6,  // 9: openclaw.thesilencer.TheSilencerAdapter.BypassDefender:input_type -> openclaw.thesilencer.BypassRequest
	13, // 10: openclaw.thesilencer.TheSilencerAdapter.Execute:output_type -> openclaw.core.OperationResponse
	14, // 11: openclaw.thesilencer.TheSilencerAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	15, // 12: openclaw.thesilencer.TheSilencerAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	1,  // 13: openclaw.thesilencer.TheSilencerAdapter.ObfuscateFile:output_type -> openclaw.thesilencer.ObfuscateResponse
	3,  // 14: openclaw.thesilencer.TheSilencerAdapter.DetectAV:output_type -> openclaw.thesilencer.DetectionResponse
	5,  // 15: openclaw.thesilencer.TheSilencerAdapter.CleanTraces:output_type -> openclaw.thesilencer.CleanupResponse
	7,  // 16: openclaw.thesilencer.TheSilencerAdapter.BypassDefender:output_type -> openclaw.thesilencer.BypassResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_thesilencer_proto_init() }
func file_thesilencer_proto_init() {
	if File_thesilencer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thesilencer_proto_rawDesc), len(file_thesilencer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thesilencer_proto_goTypes,
		DependencyIndexes: file_thesilencer_proto_depIdxs,
		MessageInfos:      file_thesilencer_proto_msgTypes,
	}.Build()
	File_thesilencer_proto = out.File
	file_thesilencer_proto_goTypes = nil
	file_thesilencer_proto_depIdxs = nil
}
