// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: thesilencer.proto

package thesilencer

import (
	context "context"
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TheSilencerAdapter_Execute_FullMethodName         = "/openclaw.thesilencer.TheSilencerAdapter/Execute"
	TheSilencerAdapter_GetCapabilities_FullMethodName = "/openclaw.thesilencer.TheSilencerAdapter/GetCapabilities"
	TheSilencerAdapter_HealthCheck_FullMethodName     = "/openclaw.thesilencer.TheSilencerAdapter/HealthCheck"
	TheSilencerAdapter_ObfuscateFile_FullMethodName   = "/openclaw.thesilencer.TheSilencerAdapter/ObfuscateFile"
	TheSilencerAdapter_DetectAV_FullMethodName        = "/openclaw.thesilencer.TheSilencerAdapter/DetectAV"
	TheSilencerAdapter_CleanTraces_FullMethodName     = "/openclaw.thesilencer.TheSilencerAdapter/CleanTraces"
	TheSilencerAdapter_BypassDefender_FullMethodName  = "/openclaw.thesilencer.TheSilencerAdapter/BypassDefender"
)

// TheSilencerAdapterClient is the client API for TheSilencerAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TheSilencer Adapter Service
type TheSilencerAdapterClient interface {
	Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error)
	GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error)
	HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error)
	// TheSilencer specific functions
	ObfuscateFile(ctx context.Context, in *ObfuscateRequest, opts ...grpc.CallOption) (*ObfuscateResponse, error)
	DetectAV(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
	CleanTraces(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error)
	BypassDefender(ctx context.Context, in *BypassRequest, opts ...grpc.CallOption) (*BypassResponse, error)
}

type theSilencerAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewTheSilencerAdapterClient(cc grpc.ClientConnInterface) TheSilencerAdapterClient {
	return &theSilencerAdapterClient{cc}
}

func (c *theSilencerAdapterClient) Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.OperationResponse)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.CapabilityList)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.HealthStatus)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) ObfuscateFile(ctx context.Context, in *ObfuscateRequest, opts ...grpc.CallOption) (*ObfuscateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObfuscateResponse)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_ObfuscateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) DetectAV(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_DetectAV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) CleanTraces(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupResponse)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_CleanTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theSilencerAdapterClient) BypassDefender(ctx context.Context, in *BypassRequest, opts ...grpc.CallOption) (*BypassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BypassResponse)
	err := c.cc.Invoke(ctx, TheSilencerAdapter_BypassDefender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheSilencerAdapterServer is the server API for TheSilencerAdapter service.
// All implementations must embed UnimplementedTheSilencerAdapterServer
// for forward compatibility.
//
// TheSilencer Adapter Service
type TheSilencerAdapterServer interface {
	Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error)
	GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error)
	HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error)
	// TheSilencer specific functions
	ObfuscateFile(context.Context, *ObfuscateRequest) (*ObfuscateResponse, error)
	DetectAV(context.Context, *DetectionRequest) (*DetectionResponse, error)
	CleanTraces(context.Context, *CleanupRequest) (*CleanupResponse, error)
	BypassDefender(context.Context, *BypassRequest) (*BypassResponse, error)
	mustEmbedUnimplementedTheSilencerAdapterServer()
}

// UnimplementedTheSilencerAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTheSilencerAdapterServer struct{}

func (UnimplementedTheSilencerAdapterServer) Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedTheSilencerAdapterServer) GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedTheSilencerAdapterServer) HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTheSilencerAdapterServer) ObfuscateFile(context.Context, *ObfuscateRequest) (*ObfuscateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObfuscateFile not implemented")
}
func (UnimplementedTheSilencerAdapterServer) DetectAV(context.Context, *DetectionRequest) (*DetectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAV not implemented")
}
func (UnimplementedTheSilencerAdapterServer) CleanTraces(context.Context, *CleanupRequest) (*CleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanTraces not implemented")
}
func (UnimplementedTheSilencerAdapterServer) BypassDefender(context.Context, *BypassRequest) (*BypassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BypassDefender not implemented")
}
func (UnimplementedTheSilencerAdapterServer) mustEmbedUnimplementedTheSilencerAdapterServer() {}
func (UnimplementedTheSilencerAdapterServer) testEmbeddedByValue()                            {}

// UnsafeTheSilencerAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TheSilencerAdapterServer will
// result in compilation errors.
type UnsafeTheSilencerAdapterServer interface {
	mustEmbedUnimplementedTheSilencerAdapterServer()
}

func RegisterTheSilencerAdapterServer(s grpc.ServiceRegistrar, srv TheSilencerAdapterServer) {
	// If the following call panics, it indicates UnimplementedTheSilencerAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TheSilencerAdapter_ServiceDesc, srv)
}

func _TheSilencerAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).Execute(ctx, req.(*core.OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).GetCapabilities(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).HealthCheck(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_ObfuscateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObfuscateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).ObfuscateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_ObfuscateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).ObfuscateFile(ctx, req.(*ObfuscateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_DetectAV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).DetectAV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_DetectAV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).DetectAV(ctx, req.(*DetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_CleanTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).CleanTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_CleanTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).CleanTraces(ctx, req.(*CleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheSilencerAdapter_BypassDefender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BypassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheSilencerAdapterServer).BypassDefender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheSilencerAdapter_BypassDefender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheSilencerAdapterServer).BypassDefender(ctx, req.(*BypassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TheSilencerAdapter_ServiceDesc is the grpc.ServiceDesc for TheSilencerAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TheSilencerAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.thesilencer.TheSilencerAdapter",
	HandlerType: (*TheSilencerAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _TheSilencerAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _TheSilencerAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TheSilencerAdapter_HealthCheck_Handler,
		},
		{
			MethodName: "ObfuscateFile",
			Handler:    _TheSilencerAdapter_ObfuscateFile_Handler,
		},
		{
			MethodName: "DetectAV",
			Handler:    _TheSilencerAdapter_DetectAV_Handler,
		},
		{
			MethodName: "CleanTraces",
			Handler:    _TheSilencerAdapter_CleanTraces_Handler,
		},
		{
			MethodName: "BypassDefender",
			Handler:    _TheSilencerAdapter_BypassDefender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thesilencer.proto",
}
