// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: villager_ai.proto

package villager_ai

import (
	context "context"
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VillagerAIAdapter_Execute_FullMethodName                      = "/openclaw.villager_ai.VillagerAIAdapter/Execute"
	VillagerAIAdapter_GetCapabilities_FullMethodName              = "/openclaw.villager_ai.VillagerAIAdapter/GetCapabilities"
	VillagerAIAdapter_HealthCheck_FullMethodName                  = "/openclaw.villager_ai.VillagerAIAdapter/HealthCheck"
	VillagerAIAdapter_GenerateStealthyPayload_FullMethodName      = "/openclaw.villager_ai.VillagerAIAdapter/GenerateStealthyPayload"
	VillagerAIAdapter_LaunchCovertPhishing_FullMethodName         = "/openclaw.villager_ai.VillagerAIAdapter/LaunchCovertPhishing"
	VillagerAIAdapter_AutomatedExfiltration_FullMethodName        = "/openclaw.villager_ai.VillagerAIAdapter/AutomatedExfiltration"
	VillagerAIAdapter_DeployCovertC2AndPersistence_FullMethodName = "/openclaw.villager_ai.VillagerAIAdapter/DeployCovertC2AndPersistence"
)

// VillagerAIAdapterClient is the client API for VillagerAIAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Villager-AI Adapter Service, provides advanced fusion capabilities
type VillagerAIAdapterClient interface {
	Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error)
	GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error)
	HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error)
	// Advanced Fusion Functions
	GenerateStealthyPayload(ctx context.Context, in *GenerateStealthyPayloadRequest, opts ...grpc.CallOption) (*GenerateStealthyPayloadResponse, error)
	LaunchCovertPhishing(ctx context.Context, in *LaunchCovertPhishingRequest, opts ...grpc.CallOption) (*LaunchCovertPhishingResponse, error)
	AutomatedExfiltration(ctx context.Context, in *AutomatedExfiltrationRequest, opts ...grpc.CallOption) (*AutomatedExfiltrationResponse, error)
	DeployCovertC2AndPersistence(ctx context.Context, in *DeployC2PersistenceRequest, opts ...grpc.CallOption) (*DeployC2PersistenceResponse, error)
}

type villagerAIAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewVillagerAIAdapterClient(cc grpc.ClientConnInterface) VillagerAIAdapterClient {
	return &villagerAIAdapterClient{cc}
}

func (c *villagerAIAdapterClient) Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.OperationResponse)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.CapabilityList)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.HealthStatus)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) GenerateStealthyPayload(ctx context.Context, in *GenerateStealthyPayloadRequest, opts ...grpc.CallOption) (*GenerateStealthyPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateStealthyPayloadResponse)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_GenerateStealthyPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) LaunchCovertPhishing(ctx context.Context, in *LaunchCovertPhishingRequest, opts ...grpc.CallOption) (*LaunchCovertPhishingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchCovertPhishingResponse)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_LaunchCovertPhishing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) AutomatedExfiltration(ctx context.Context, in *AutomatedExfiltrationRequest, opts ...grpc.CallOption) (*AutomatedExfiltrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomatedExfiltrationResponse)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_AutomatedExfiltration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *villagerAIAdapterClient) DeployCovertC2AndPersistence(ctx context.Context, in *DeployC2PersistenceRequest, opts ...grpc.CallOption) (*DeployC2PersistenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployC2PersistenceResponse)
	err := c.cc.Invoke(ctx, VillagerAIAdapter_DeployCovertC2AndPersistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VillagerAIAdapterServer is the server API for VillagerAIAdapter service.
// All implementations must embed UnimplementedVillagerAIAdapterServer
// for forward compatibility.
//
// Villager-AI Adapter Service, provides advanced fusion capabilities
type VillagerAIAdapterServer interface {
	Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error)
	GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error)
	HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error)
	// Advanced Fusion Functions
	GenerateStealthyPayload(context.Context, *GenerateStealthyPayloadRequest) (*GenerateStealthyPayloadResponse, error)
	LaunchCovertPhishing(context.Context, *LaunchCovertPhishingRequest) (*LaunchCovertPhishingResponse, error)
	AutomatedExfiltration(context.Context, *AutomatedExfiltrationRequest) (*AutomatedExfiltrationResponse, error)
	DeployCovertC2AndPersistence(context.Context, *DeployC2PersistenceRequest) (*DeployC2PersistenceResponse, error)
	mustEmbedUnimplementedVillagerAIAdapterServer()
}

// UnimplementedVillagerAIAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVillagerAIAdapterServer struct{}

func (UnimplementedVillagerAIAdapterServer) Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedVillagerAIAdapterServer) GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedVillagerAIAdapterServer) HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVillagerAIAdapterServer) GenerateStealthyPayload(context.Context, *GenerateStealthyPayloadRequest) (*GenerateStealthyPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStealthyPayload not implemented")
}
func (UnimplementedVillagerAIAdapterServer) LaunchCovertPhishing(context.Context, *LaunchCovertPhishingRequest) (*LaunchCovertPhishingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchCovertPhishing not implemented")
}
func (UnimplementedVillagerAIAdapterServer) AutomatedExfiltration(context.Context, *AutomatedExfiltrationRequest) (*AutomatedExfiltrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutomatedExfiltration not implemented")
}
func (UnimplementedVillagerAIAdapterServer) DeployCovertC2AndPersistence(context.Context, *DeployC2PersistenceRequest) (*DeployC2PersistenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployCovertC2AndPersistence not implemented")
}
func (UnimplementedVillagerAIAdapterServer) mustEmbedUnimplementedVillagerAIAdapterServer() {}
func (UnimplementedVillagerAIAdapterServer) testEmbeddedByValue()                           {}

// UnsafeVillagerAIAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VillagerAIAdapterServer will
// result in compilation errors.
type UnsafeVillagerAIAdapterServer interface {
	mustEmbedUnimplementedVillagerAIAdapterServer()
}

func RegisterVillagerAIAdapterServer(s grpc.ServiceRegistrar, srv VillagerAIAdapterServer) {
	// If the following call panics, it indicates UnimplementedVillagerAIAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VillagerAIAdapter_ServiceDesc, srv)
}

func _VillagerAIAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).Execute(ctx, req.(*core.OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).GetCapabilities(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).HealthCheck(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_GenerateStealthyPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateStealthyPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).GenerateStealthyPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_GenerateStealthyPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).GenerateStealthyPayload(ctx, req.(*GenerateStealthyPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_LaunchCovertPhishing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchCovertPhishingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).LaunchCovertPhishing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_LaunchCovertPhishing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).LaunchCovertPhishing(ctx, req.(*LaunchCovertPhishingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_AutomatedExfiltration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutomatedExfiltrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).AutomatedExfiltration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_AutomatedExfiltration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).AutomatedExfiltration(ctx, req.(*AutomatedExfiltrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VillagerAIAdapter_DeployCovertC2AndPersistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployC2PersistenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VillagerAIAdapterServer).DeployCovertC2AndPersistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VillagerAIAdapter_DeployCovertC2AndPersistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VillagerAIAdapterServer).DeployCovertC2AndPersistence(ctx, req.(*DeployC2PersistenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VillagerAIAdapter_ServiceDesc is the grpc.ServiceDesc for VillagerAIAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VillagerAIAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.villager_ai.VillagerAIAdapter",
	HandlerType: (*VillagerAIAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _VillagerAIAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _VillagerAIAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VillagerAIAdapter_HealthCheck_Handler,
		},
		{
			MethodName: "GenerateStealthyPayload",
			Handler:    _VillagerAIAdapter_GenerateStealthyPayload_Handler,
		},
		{
			MethodName: "LaunchCovertPhishing",
			Handler:    _VillagerAIAdapter_LaunchCovertPhishing_Handler,
		},
		{
			MethodName: "AutomatedExfiltration",
			Handler:    _VillagerAIAdapter_AutomatedExfiltration_Handler,
		},
		{
			MethodName: "DeployCovertC2AndPersistence",
			Handler:    _VillagerAIAdapter_DeployCovertC2AndPersistence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "villager_ai.proto",
}
