// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: villager_ai.proto

package villager_ai

import (
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	_ "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/hexstrike"
	_ "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/netrunners"
	thesilencer "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/thesilencer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateStealthyPayloadRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BasePayloadType      string                 `protobuf:"bytes,1,opt,name=base_payload_type,json=basePayloadType,proto3" json:"base_payload_type,omitempty"`                                                                                  // e.g., "hta", "exe", "meterpreter"
	ObfuscationTechnique string                 `protobuf:"bytes,2,opt,name=obfuscation_technique,json=obfuscationTechnique,proto3" json:"obfuscation_technique,omitempty"`                                                                     // e.g., "polymorphic", "av_bypass"
	HexstrikeOptions     map[string]string      `protobuf:"bytes,3,rep,name=hexstrike_options,json=hexstrikeOptions,proto3" json:"hexstrike_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // Additional options for Hexstrike payload generation
	ThesilencerOptions   map[string]string      `protobuf:"bytes,4,rep,name=thesilencer_options,json=thesilencerOptions,proto3" json:"thesilencer_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional options for TheSilencer obfuscation
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateStealthyPayloadRequest) Reset() {
	*x = GenerateStealthyPayloadRequest{}
	mi := &file_villager_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStealthyPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStealthyPayloadRequest) ProtoMessage() {}

func (x *GenerateStealthyPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStealthyPayloadRequest.ProtoReflect.Descriptor instead.
func (*GenerateStealthyPayloadRequest) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateStealthyPayloadRequest) GetBasePayloadType() string {
	if x != nil {
		return x.BasePayloadType
	}
	return ""
}

func (x *GenerateStealthyPayloadRequest) GetObfuscationTechnique() string {
	if x != nil {
		return x.ObfuscationTechnique
	}
	return ""
}

func (x *GenerateStealthyPayloadRequest) GetHexstrikeOptions() map[string]string {
	if x != nil {
		return x.HexstrikeOptions
	}
	return nil
}

func (x *GenerateStealthyPayloadRequest) GetThesilencerOptions() map[string]string {
	if x != nil {
		return x.ThesilencerOptions
	}
	return nil
}

type GenerateStealthyPayloadResponse struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	FinalPayloadPath string                         `protobuf:"bytes,1,opt,name=final_payload_path,json=finalPayloadPath,proto3" json:"final_payload_path,omitempty"`
	OriginalHash     string                         `protobuf:"bytes,2,opt,name=original_hash,json=originalHash,proto3" json:"original_hash,omitempty"`
	ObfuscatedHash   string                         `protobuf:"bytes,3,opt,name=obfuscated_hash,json=obfuscatedHash,proto3" json:"obfuscated_hash,omitempty"`
	DetectionResults *thesilencer.DetectionResponse `protobuf:"bytes,4,opt,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty"` // Detection results after obfuscation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateStealthyPayloadResponse) Reset() {
	*x = GenerateStealthyPayloadResponse{}
	mi := &file_villager_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStealthyPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStealthyPayloadResponse) ProtoMessage() {}

func (x *GenerateStealthyPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStealthyPayloadResponse.ProtoReflect.Descriptor instead.
func (*GenerateStealthyPayloadResponse) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateStealthyPayloadResponse) GetFinalPayloadPath() string {
	if x != nil {
		return x.FinalPayloadPath
	}
	return ""
}

func (x *GenerateStealthyPayloadResponse) GetOriginalHash() string {
	if x != nil {
		return x.OriginalHash
	}
	return ""
}

func (x *GenerateStealthyPayloadResponse) GetObfuscatedHash() string {
	if x != nil {
		return x.ObfuscatedHash
	}
	return ""
}

func (x *GenerateStealthyPayloadResponse) GetDetectionResults() *thesilencer.DetectionResponse {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

type LaunchCovertPhishingRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CampaignName              string                 `protobuf:"bytes,1,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	PayloadPath               string                 `protobuf:"bytes,2,opt,name=payload_path,json=payloadPath,proto3" json:"payload_path,omitempty"` // Path to the already generated stealthy payload
	PhishingTemplate          string                 `protobuf:"bytes,3,opt,name=phishing_template,json=phishingTemplate,proto3" json:"phishing_template,omitempty"`
	Recipients                []string               `protobuf:"bytes,4,rep,name=recipients,proto3" json:"recipients,omitempty"`
	HexstrikeEmailOptions     map[string]string      `protobuf:"bytes,5,rep,name=hexstrike_email_options,json=hexstrikeEmailOptions,proto3" json:"hexstrike_email_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`             // Options for Hexstrike email sending
	NetrunnersDeliveryOptions map[string]string      `protobuf:"bytes,6,rep,name=netrunners_delivery_options,json=netrunnersDeliveryOptions,proto3" json:"netrunners_delivery_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Options for Net-Runners covert delivery
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LaunchCovertPhishingRequest) Reset() {
	*x = LaunchCovertPhishingRequest{}
	mi := &file_villager_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCovertPhishingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCovertPhishingRequest) ProtoMessage() {}

func (x *LaunchCovertPhishingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCovertPhishingRequest.ProtoReflect.Descriptor instead.
func (*LaunchCovertPhishingRequest) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{2}
}

func (x *LaunchCovertPhishingRequest) GetCampaignName() string {
	if x != nil {
		return x.CampaignName
	}
	return ""
}

func (x *LaunchCovertPhishingRequest) GetPayloadPath() string {
	if x != nil {
		return x.PayloadPath
	}
	return ""
}

func (x *LaunchCovertPhishingRequest) GetPhishingTemplate() string {
	if x != nil {
		return x.PhishingTemplate
	}
	return ""
}

func (x *LaunchCovertPhishingRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *LaunchCovertPhishingRequest) GetHexstrikeEmailOptions() map[string]string {
	if x != nil {
		return x.HexstrikeEmailOptions
	}
	return nil
}

func (x *LaunchCovertPhishingRequest) GetNetrunnersDeliveryOptions() map[string]string {
	if x != nil {
		return x.NetrunnersDeliveryOptions
	}
	return nil
}

type LaunchCovertPhishingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SentCount        int32                  `protobuf:"varint,2,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	FailedRecipients []string               `protobuf:"bytes,3,rep,name=failed_recipients,json=failedRecipients,proto3" json:"failed_recipients,omitempty"`
	CampaignId       string                 `protobuf:"bytes,4,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LaunchCovertPhishingResponse) Reset() {
	*x = LaunchCovertPhishingResponse{}
	mi := &file_villager_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCovertPhishingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCovertPhishingResponse) ProtoMessage() {}

func (x *LaunchCovertPhishingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCovertPhishingResponse.ProtoReflect.Descriptor instead.
func (*LaunchCovertPhishingResponse) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{3}
}

func (x *LaunchCovertPhishingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LaunchCovertPhishingResponse) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *LaunchCovertPhishingResponse) GetFailedRecipients() []string {
	if x != nil {
		return x.FailedRecipients
	}
	return nil
}

func (x *LaunchCovertPhishingResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type AutomatedExfiltrationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SourceDataPath            string                 `protobuf:"bytes,1,opt,name=source_data_path,json=sourceDataPath,proto3" json:"source_data_path,omitempty"`
	DestinationEndpoint       string                 `protobuf:"bytes,2,opt,name=destination_endpoint,json=destinationEndpoint,proto3" json:"destination_endpoint,omitempty"`                                                                                               // e.g., "s3://bucket", "dns_server.com"
	ExfiltrationMethod        string                 `protobuf:"bytes,3,opt,name=exfiltration_method,json=exfiltrationMethod,proto3" json:"exfiltration_method,omitempty"`                                                                                                  // e.g., "dns_tunnel", "https_covert"
	NetrunnersOptions         map[string]string      `protobuf:"bytes,4,rep,name=netrunners_options,json=netrunnersOptions,proto3" json:"netrunners_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                           // Options for Net-Runners exfiltration
	ThesilencerCleanupOptions map[string]string      `protobuf:"bytes,5,rep,name=thesilencer_cleanup_options,json=thesilencerCleanupOptions,proto3" json:"thesilencer_cleanup_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Options for cleaning traces with TheSilencer
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AutomatedExfiltrationRequest) Reset() {
	*x = AutomatedExfiltrationRequest{}
	mi := &file_villager_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomatedExfiltrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomatedExfiltrationRequest) ProtoMessage() {}

func (x *AutomatedExfiltrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomatedExfiltrationRequest.ProtoReflect.Descriptor instead.
func (*AutomatedExfiltrationRequest) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AutomatedExfiltrationRequest) GetSourceDataPath() string {
	if x != nil {
		return x.SourceDataPath
	}
	return ""
}

func (x *AutomatedExfiltrationRequest) GetDestinationEndpoint() string {
	if x != nil {
		return x.DestinationEndpoint
	}
	return ""
}

func (x *AutomatedExfiltrationRequest) GetExfiltrationMethod() string {
	if x != nil {
		return x.ExfiltrationMethod
	}
	return ""
}

func (x *AutomatedExfiltrationRequest) GetNetrunnersOptions() map[string]string {
	if x != nil {
		return x.NetrunnersOptions
	}
	return nil
}

func (x *AutomatedExfiltrationRequest) GetThesilencerCleanupOptions() map[string]string {
	if x != nil {
		return x.ThesilencerCleanupOptions
	}
	return nil
}

type AutomatedExfiltrationResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Success                bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExfiltrationReportPath string                 `protobuf:"bytes,2,opt,name=exfiltration_report_path,json=exfiltrationReportPath,proto3" json:"exfiltration_report_path,omitempty"`
	TotalBytesExfiltrated  int32                  `protobuf:"varint,3,opt,name=total_bytes_exfiltrated,json=totalBytesExfiltrated,proto3" json:"total_bytes_exfiltrated,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AutomatedExfiltrationResponse) Reset() {
	*x = AutomatedExfiltrationResponse{}
	mi := &file_villager_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomatedExfiltrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomatedExfiltrationResponse) ProtoMessage() {}

func (x *AutomatedExfiltrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomatedExfiltrationResponse.ProtoReflect.Descriptor instead.
func (*AutomatedExfiltrationResponse) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AutomatedExfiltrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AutomatedExfiltrationResponse) GetExfiltrationReportPath() string {
	if x != nil {
		return x.ExfiltrationReportPath
	}
	return ""
}

func (x *AutomatedExfiltrationResponse) GetTotalBytesExfiltrated() int32 {
	if x != nil {
		return x.TotalBytesExfiltrated
	}
	return 0
}

type DeployC2PersistenceRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	PayloadPath                 string                 `protobuf:"bytes,1,opt,name=payload_path,json=payloadPath,proto3" json:"payload_path,omitempty"`                                                                                                                             // Payload for persistence
	PersistenceMethod           string                 `protobuf:"bytes,2,opt,name=persistence_method,json=persistenceMethod,proto3" json:"persistence_method,omitempty"`                                                                                                           // e.g., "registry", "scheduled_task", "startup_item"
	C2Protocol                  string                 `protobuf:"bytes,3,opt,name=c2_protocol,json=c2Protocol,proto3" json:"c2_protocol,omitempty"`                                                                                                                                // e.g., "https", "dns"
	NetrunnersC2Options         map[string]string      `protobuf:"bytes,4,rep,name=netrunners_c2_options,json=netrunnersC2Options,proto3" json:"netrunners_c2_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                         // Options for Net-Runners C2 setup
	HexstrikePersistenceOptions map[string]string      `protobuf:"bytes,5,rep,name=hexstrike_persistence_options,json=hexstrikePersistenceOptions,proto3" json:"hexstrike_persistence_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Options for Hexstrike persistence
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeployC2PersistenceRequest) Reset() {
	*x = DeployC2PersistenceRequest{}
	mi := &file_villager_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployC2PersistenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployC2PersistenceRequest) ProtoMessage() {}

func (x *DeployC2PersistenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployC2PersistenceRequest.ProtoReflect.Descriptor instead.
func (*DeployC2PersistenceRequest) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{6}
}

func (x *DeployC2PersistenceRequest) GetPayloadPath() string {
	if x != nil {
		return x.PayloadPath
	}
	return ""
}

func (x *DeployC2PersistenceRequest) GetPersistenceMethod() string {
	if x != nil {
		return x.PersistenceMethod
	}
	return ""
}

func (x *DeployC2PersistenceRequest) GetC2Protocol() string {
	if x != nil {
		return x.C2Protocol
	}
	return ""
}

func (x *DeployC2PersistenceRequest) GetNetrunnersC2Options() map[string]string {
	if x != nil {
		return x.NetrunnersC2Options
	}
	return nil
}

func (x *DeployC2PersistenceRequest) GetHexstrikePersistenceOptions() map[string]string {
	if x != nil {
		return x.HexstrikePersistenceOptions
	}
	return nil
}

type DeployC2PersistenceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	C2ListenerInfo    string                 `protobuf:"bytes,2,opt,name=c2_listener_info,json=c2ListenerInfo,proto3" json:"c2_listener_info,omitempty"`
	PersistenceReport string                 `protobuf:"bytes,3,opt,name=persistence_report,json=persistenceReport,proto3" json:"persistence_report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployC2PersistenceResponse) Reset() {
	*x = DeployC2PersistenceResponse{}
	mi := &file_villager_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployC2PersistenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployC2PersistenceResponse) ProtoMessage() {}

func (x *DeployC2PersistenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_villager_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployC2PersistenceResponse.ProtoReflect.Descriptor instead.
func (*DeployC2PersistenceResponse) Descriptor() ([]byte, []int) {
	return file_villager_ai_proto_rawDescGZIP(), []int{7}
}

func (x *DeployC2PersistenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployC2PersistenceResponse) GetC2ListenerInfo() string {
	if x != nil {
		return x.C2ListenerInfo
	}
	return ""
}

func (x *DeployC2PersistenceResponse) GetPersistenceReport() string {
	if x != nil {
		return x.PersistenceReport
	}
	return ""
}

var File_villager_ai_proto protoreflect.FileDescriptor

const file_villager_ai_proto_rawDesc = "" +
	"\n" +
	"\x11villager_ai.proto\x12\x14openclaw.villager_ai\x1a\n" +
	"core.proto\x1a\x0fhexstrike.proto\x1a\x11thesilencer.proto\x1a\x10netrunners.proto\"\x85\x04\n" +
	"\x1eGenerateStealthyPayloadRequest\x12*\n" +
	"\x11base_payload_type\x18\x01 \x01(\tR\x0fbasePayloadType\x123\n" +
	"\x15obfuscation_technique\x18\x02 \x01(\tR\x14obfuscationTechnique\x12w\n" +
	"\x11hexstrike_options\x18\x03 \x03(\v2J.openclaw.villager_ai.GenerateStealthyPayloadRequest.HexstrikeOptionsEntryR\x10hexstrikeOptions\x12}\n" +
	"\x13thesilencer_options\x18\x04 \x03(\v2L.openclaw.villager_ai.GenerateStealthyPayloadRequest.ThesilencerOptionsEntryR\x12thesilencerOptions\x1aC\n" +
	"\x15HexstrikeOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ThesilencerOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x1fGenerateStealthyPayloadResponse\x12,\n" +
	"\x12final_payload_path\x18\x01 \x01(\tR\x10finalPayloadPath\x12#\n" +
	"\roriginal_hash\x18\x02 \x01(\tR\foriginalHash\x12'\n" +
	"\x0fobfuscated_hash\x18\x03 \x01(\tR\x0eobfuscatedHash\x12T\n" +
	"\x11detection_results\x18\x04 \x01(\v2'.openclaw.thesilencer.DetectionResponseR\x10detectionResults\"\xe4\x04\n" +
	"\x1bLaunchCovertPhishingRequest\x12#\n" +
	"\rcampaign_name\x18\x01 \x01(\tR\fcampaignName\x12!\n" +
	"\fpayload_path\x18\x02 \x01(\tR\vpayloadPath\x12+\n" +
	"\x11phishing_template\x18\x03 \x01(\tR\x10phishingTemplate\x12\x1e\n" +
	"\n" +
	"recipients\x18\x04 \x03(\tR\n" +
	"recipients\x12\x84\x01\n" +
	"\x17hexstrike_email_options\x18\x05 \x03(\v2L.openclaw.villager_ai.LaunchCovertPhishingRequest.HexstrikeEmailOptionsEntryR\x15hexstrikeEmailOptions\x12\x90\x01\n" +
	"\x1bnetrunners_delivery_options\x18\x06 \x03(\v2P.openclaw.villager_ai.LaunchCovertPhishingRequest.NetrunnersDeliveryOptionsEntryR\x19netrunnersDeliveryOptions\x1aH\n" +
	"\x1aHexstrikeEmailOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aL\n" +
	"\x1eNetrunnersDeliveryOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x1cLaunchCovertPhishingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x02 \x01(\x05R\tsentCount\x12+\n" +
	"\x11failed_recipients\x18\x03 \x03(\tR\x10failedRecipients\x12\x1f\n" +
	"\vcampaign_id\x18\x04 \x01(\tR\n" +
	"campaignId\"\xce\x04\n" +
	"\x1cAutomatedExfiltrationRequest\x12(\n" +
	"\x10source_data_path\x18\x01 \x01(\tR\x0esourceDataPath\x121\n" +
	"\x14destination_endpoint\x18\x02 \x01(\tR\x13destinationEndpoint\x12/\n" +
	"\x13exfiltration_method\x18\x03 \x01(\tR\x12exfiltrationMethod\x12x\n" +
	"\x12netrunners_options\x18\x04 \x03(\v2I.openclaw.villager_ai.AutomatedExfiltrationRequest.NetrunnersOptionsEntryR\x11netrunnersOptions\x12\x91\x01\n" +
	"\x1bthesilencer_cleanup_options\x18\x05 \x03(\v2Q.openclaw.villager_ai.AutomatedExfiltrationRequest.ThesilencerCleanupOptionsEntryR\x19thesilencerCleanupOptions\x1aD\n" +
	"\x16NetrunnersOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aL\n" +
	"\x1eThesilencerCleanupOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x1dAutomatedExfiltrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x18exfiltration_report_path\x18\x02 \x01(\tR\x16exfiltrationReportPath\x126\n" +
	"\x17total_bytes_exfiltrated\x18\x03 \x01(\x05R\x15totalBytesExfiltrated\"\xbe\x04\n" +
	"\x1aDeployC2PersistenceRequest\x12!\n" +
	"\fpayload_path\x18\x01 \x01(\tR\vpayloadPath\x12-\n" +
	"\x12persistence_method\x18\x02 \x01(\tR\x11persistenceMethod\x12\x1f\n" +
	"\vc2_protocol\x18\x03 \x01(\tR\n" +
	"c2Protocol\x12}\n" +
	"\x15netrunners_c2_options\x18\x04 \x03(\v2I.openclaw.villager_ai.DeployC2PersistenceRequest.NetrunnersC2OptionsEntryR\x13netrunnersC2Options\x12\x95\x01\n" +
	"\x1dhexstrike_persistence_options\x18\x05 \x03(\v2Q.openclaw.villager_ai.DeployC2PersistenceRequest.HexstrikePersistenceOptionsEntryR\x1bhexstrikePersistenceOptions\x1aF\n" +
	"\x18NetrunnersC2OptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aN\n" +
	" HexstrikePersistenceOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x1bDeployC2PersistenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x10c2_listener_info\x18\x02 \x01(\tR\x0ec2ListenerInfo\x12-\n" +
	"\x12persistence_report\x18\x03 \x01(\tR\x11persistenceReport2\xfc\x05\n" +
	"\x11VillagerAIAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatus\x12\x86\x01\n" +
	"\x17GenerateStealthyPayload\x124.openclaw.villager_ai.GenerateStealthyPayloadRequest\x1a5.openclaw.villager_ai.GenerateStealthyPayloadResponse\x12}\n" +
	"\x14LaunchCovertPhishing\x121.openclaw.villager_ai.LaunchCovertPhishingRequest\x1a2.openclaw.villager_ai.LaunchCovertPhishingResponse\x12\x80\x01\n" +
	"\x15AutomatedExfiltration\x122.openclaw.villager_ai.AutomatedExfiltrationRequest\x1a3.openclaw.villager_ai.AutomatedExfiltrationResponse\x12\x83\x01\n" +
	"\x1cDeployCovertC2AndPersistence\x120.openclaw.villager_ai.DeployC2PersistenceRequest\x1a1.openclaw.villager_ai.DeployC2PersistenceResponseBAZ?github.com/OpenClaw-Security/Stealth-Core/pkg/proto/villager_aib\x06proto3"

var (
	file_villager_ai_proto_rawDescOnce sync.Once
	file_villager_ai_proto_rawDescData []byte
)

func file_villager_ai_proto_rawDescGZIP() []byte {
	file_villager_ai_proto_rawDescOnce.Do(func() {
		file_villager_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_villager_ai_proto_rawDesc), len(file_villager_ai_proto_rawDesc)))
	})
	return file_villager_ai_proto_rawDescData
}

var file_villager_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_villager_ai_proto_goTypes = []any{
	(*GenerateStealthyPayloadRequest)(nil),  // 0: openclaw.villager_ai.GenerateStealthyPayloadRequest
	(*GenerateStealthyPayloadResponse)(nil), // 1: openclaw.villager_ai.GenerateStealthyPayloadResponse
	(*LaunchCovertPhishingRequest)(nil),     // 2: openclaw.villager_ai.LaunchCovertPhishingRequest
	(*LaunchCovertPhishingResponse)(nil),    // 3: openclaw.villager_ai.LaunchCovertPhishingResponse
	(*AutomatedExfiltrationRequest)(nil),    // 4: openclaw.villager_ai.AutomatedExfiltrationRequest
	(*AutomatedExfiltrationResponse)(nil),   // 5: openclaw.villager_ai.AutomatedExfiltrationResponse
	(*DeployC2PersistenceRequest)(nil),      // 6: openclaw.villager_ai.DeployC2PersistenceRequest
	(*DeployC2PersistenceResponse)(nil),     // 7: openclaw.villager_ai.DeployC2PersistenceResponse
	nil,                                     // 8: openclaw.villager_ai.GenerateStealthyPayloadRequest.HexstrikeOptionsEntry
	nil,                                     // 9: openclaw.villager_ai.GenerateStealthyPayloadRequest.ThesilencerOptionsEntry
	nil,                                     // 10: openclaw.villager_ai.LaunchCovertPhishingRequest.HexstrikeEmailOptionsEntry
	nil,                                     // 11: openclaw.villager_ai.LaunchCovertPhishingRequest.NetrunnersDeliveryOptionsEntry
	nil,                                     // 12: openclaw.villager_ai.AutomatedExfiltrationRequest.NetrunnersOptionsEntry
	nil,                                     // 13: openclaw.villager_ai.AutomatedExfiltrationRequest.ThesilencerCleanupOptionsEntry
	nil,                                     // 14: openclaw.villager_ai.DeployC2PersistenceRequest.NetrunnersC2OptionsEntry
	nil,                                     // 15: openclaw.villager_ai.DeployC2PersistenceRequest.HexstrikePersistenceOptionsEntry
	(*thesilencer.DetectionResponse)(nil),   // 16: openclaw.thesilencer.DetectionResponse
	(*core.OperationRequest)(nil),           // 17: openclaw.core.OperationRequest
	(*core.Empty)(nil),                      // 18: openclaw.core.Empty
	(*core.OperationResponse)(nil),          // 19: openclaw.core.OperationResponse
	(*core.CapabilityList)(nil),             // 20: openclaw.core.CapabilityList
	(*core.HealthStatus)(nil),               // 21: openclaw.core.HealthStatus
}
var file_villager_ai_proto_depIdxs = []int32{
	8,  // 0: openclaw.villager_ai.GenerateStealthyPayloadRequest.hexstrike_options:type_name -> openclaw.villager_ai.GenerateStealthyPayloadRequest.HexstrikeOptionsEntry
	9,  // 1: openclaw.villager_ai.GenerateStealthyPayloadRequest.thesilencer_options:type_name -> openclaw.villager_ai.GenerateStealthyPayloadRequest.ThesilencerOptionsEntry
	16, // 2: openclaw.villager_ai.GenerateStealthyPayloadResponse.detection_results:type_name -> openclaw.thesilencer.DetectionResponse
	10, // 3: openclaw.villager_ai.LaunchCovertPhishingRequest.hexstrike_email_options:type_name -> openclaw.villager_ai.LaunchCovertPhishingRequest.HexstrikeEmailOptionsEntry
	11, // 4: openclaw.villager_ai.LaunchCovertPhishingRequest.netrunners_delivery_options:type_name -> openclaw.villager_ai.LaunchCovertPhishingRequest.NetrunnersDeliveryOptionsEntry
	12, // 5: openclaw.villager_ai.AutomatedExfiltrationRequest.netrunners_options:type_name -> openclaw.villager_ai.AutomatedExfiltrationRequest.NetrunnersOptionsEntry
	13, // 6: openclaw.villager_ai.AutomatedExfiltrationRequest.thesilencer_cleanup_options:type_name -> openclaw.villager_ai.AutomatedExfiltrationRequest.ThesilencerCleanupOptionsEntry
	14, // 7: openclaw.villager_ai.DeployC2PersistenceRequest.netrunners_c2_options:type_name -> openclaw.villager_ai.DeployC2PersistenceRequest.NetrunnersC2OptionsEntry
	15, // 8: openclaw.villager_ai.DeployC2PersistenceRequest.hexstrike_persistence_options:type_name -> openclaw.villager_ai.DeployC2PersistenceRequest.HexstrikePersistenceOptionsEntry
	17, // 9: openclaw.villager_ai.VillagerAIAdapter.Execute:input_type -> openclaw.core.OperationRequest
	18, // 10: openclaw.villager_ai.VillagerAIAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	18, // 11: openclaw.villager_ai.VillagerAIAdapter.HealthCheck:input_type -> openclaw.core.Empty
	0,  // 12: openclaw.villager_ai.VillagerAIAdapter.GenerateStealthyPayload:input_type -> openclaw.villager_ai.GenerateStealthyPayloadRequest
	2,  // 13: openclaw.villager_ai.VillagerAIAdapter.LaunchCovertPhishing:input_type -> openclaw.villager_ai.LaunchCovertPhishingRequest
	4,  // 14: openclaw.villager_ai.VillagerAIAdapter.AutomatedExfiltration:input_type -> openclaw.villager_ai.AutomatedExfiltrationRequest
	6,  // 15: openclaw.villager_ai.VillagerAIAdapter.DeployCovertC2AndPersistence:input_type -> openclaw.villager_ai.DeployC2PersistenceRequest
	19, // 16: openclaw.villager_ai.VillagerAIAdapter.Execute:output_type -> openclaw.core.OperationResponse
	20, // 17: openclaw.villager_ai.VillagerAIAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	21, // 18: openclaw.villager_ai.VillagerAIAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	1,  // 19: openclaw.villager_ai.VillagerAIAdapter.GenerateStealthyPayload:output_type -> openclaw.villager_ai.GenerateStealthyPayloadResponse
	3,  // 20: openclaw.villager_ai.VillagerAIAdapter.LaunchCovertPhishing:output_type -> openclaw.villager_ai.LaunchCovertPhishingResponse
	5,  // 21: openclaw.villager_ai.VillagerAIAdapter.AutomatedExfiltration:output_type -> openclaw.villager_ai.AutomatedExfiltrationResponse
	7,  // 22: openclaw.villager_ai.VillagerAIAdapter.DeployCovertC2AndPersistence:output_type -> openclaw.villager_ai.DeployC2PersistenceResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_villager_ai_proto_init() }
func file_villager_ai_proto_init() {
	if File_villager_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_villager_ai_proto_rawDesc), len(file_villager_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_villager_ai_proto_goTypes,
		DependencyIndexes: file_villager_ai_proto_depIdxs,
		MessageInfos:      file_villager_ai_proto_msgTypes,
	}.Build()
	File_villager_ai_proto = out.File
	file_villager_ai_proto_goTypes = nil
	file_villager_ai_proto_depIdxs = nil
}
