// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: netrunners.proto

package netrunners

import (
	context "context"
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetRunnersAdapter_Execute_FullMethodName         = "/openclaw.netrunners.NetRunnersAdapter/Execute"
	NetRunnersAdapter_GetCapabilities_FullMethodName = "/openclaw.netrunners.NetRunnersAdapter/GetCapabilities"
	NetRunnersAdapter_HealthCheck_FullMethodName     = "/openclaw.netrunners.NetRunnersAdapter/HealthCheck"
	NetRunnersAdapter_SetupListener_FullMethodName   = "/openclaw.netrunners.NetRunnersAdapter/SetupListener"
	NetRunnersAdapter_CovertChannel_FullMethodName   = "/openclaw.netrunners.NetRunnersAdapter/CovertChannel"
	NetRunnersAdapter_ExfiltrateData_FullMethodName  = "/openclaw.netrunners.NetRunnersAdapter/ExfiltrateData"
	NetRunnersAdapter_NetworkScan_FullMethodName     = "/openclaw.netrunners.NetRunnersAdapter/NetworkScan"
)

// NetRunnersAdapterClient is the client API for NetRunnersAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Net-Runners Adapter Service
type NetRunnersAdapterClient interface {
	Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error)
	GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error)
	HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error)
	// Net-Runners specific functions
	SetupListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error)
	CovertChannel(ctx context.Context, in *ChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error)
	ExfiltrateData(ctx context.Context, in *ExfiltrationRequest, opts ...grpc.CallOption) (*ExfiltrationResponse, error)
	NetworkScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type netRunnersAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewNetRunnersAdapterClient(cc grpc.ClientConnInterface) NetRunnersAdapterClient {
	return &netRunnersAdapterClient{cc}
}

func (c *netRunnersAdapterClient) Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.OperationResponse)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.CapabilityList)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.HealthStatus)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) SetupListener(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (*ListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListenerResponse)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_SetupListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) CovertChannel(ctx context.Context, in *ChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelResponse)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_CovertChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) ExfiltrateData(ctx context.Context, in *ExfiltrationRequest, opts ...grpc.CallOption) (*ExfiltrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExfiltrationResponse)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_ExfiltrateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netRunnersAdapterClient) NetworkScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, NetRunnersAdapter_NetworkScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetRunnersAdapterServer is the server API for NetRunnersAdapter service.
// All implementations must embed UnimplementedNetRunnersAdapterServer
// for forward compatibility.
//
// Net-Runners Adapter Service
type NetRunnersAdapterServer interface {
	Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error)
	GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error)
	HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error)
	// Net-Runners specific functions
	SetupListener(context.Context, *ListenerRequest) (*ListenerResponse, error)
	CovertChannel(context.Context, *ChannelRequest) (*ChannelResponse, error)
	ExfiltrateData(context.Context, *ExfiltrationRequest) (*ExfiltrationResponse, error)
	NetworkScan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedNetRunnersAdapterServer()
}

// UnimplementedNetRunnersAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetRunnersAdapterServer struct{}

func (UnimplementedNetRunnersAdapterServer) Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNetRunnersAdapterServer) GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedNetRunnersAdapterServer) HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNetRunnersAdapterServer) SetupListener(context.Context, *ListenerRequest) (*ListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupListener not implemented")
}
func (UnimplementedNetRunnersAdapterServer) CovertChannel(context.Context, *ChannelRequest) (*ChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CovertChannel not implemented")
}
func (UnimplementedNetRunnersAdapterServer) ExfiltrateData(context.Context, *ExfiltrationRequest) (*ExfiltrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExfiltrateData not implemented")
}
func (UnimplementedNetRunnersAdapterServer) NetworkScan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NetworkScan not implemented")
}
func (UnimplementedNetRunnersAdapterServer) mustEmbedUnimplementedNetRunnersAdapterServer() {}
func (UnimplementedNetRunnersAdapterServer) testEmbeddedByValue()                           {}

// UnsafeNetRunnersAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetRunnersAdapterServer will
// result in compilation errors.
type UnsafeNetRunnersAdapterServer interface {
	mustEmbedUnimplementedNetRunnersAdapterServer()
}

func RegisterNetRunnersAdapterServer(s grpc.ServiceRegistrar, srv NetRunnersAdapterServer) {
	// If the following call panics, it indicates UnimplementedNetRunnersAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetRunnersAdapter_ServiceDesc, srv)
}

func _NetRunnersAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).Execute(ctx, req.(*core.OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).GetCapabilities(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).HealthCheck(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_SetupListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).SetupListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_SetupListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).SetupListener(ctx, req.(*ListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_CovertChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).CovertChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_CovertChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).CovertChannel(ctx, req.(*ChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_ExfiltrateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExfiltrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).ExfiltrateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_ExfiltrateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).ExfiltrateData(ctx, req.(*ExfiltrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetRunnersAdapter_NetworkScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetRunnersAdapterServer).NetworkScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetRunnersAdapter_NetworkScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetRunnersAdapterServer).NetworkScan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetRunnersAdapter_ServiceDesc is the grpc.ServiceDesc for NetRunnersAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetRunnersAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.netrunners.NetRunnersAdapter",
	HandlerType: (*NetRunnersAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _NetRunnersAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _NetRunnersAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NetRunnersAdapter_HealthCheck_Handler,
		},
		{
			MethodName: "SetupListener",
			Handler:    _NetRunnersAdapter_SetupListener_Handler,
		},
		{
			MethodName: "CovertChannel",
			Handler:    _NetRunnersAdapter_CovertChannel_Handler,
		},
		{
			MethodName: "ExfiltrateData",
			Handler:    _NetRunnersAdapter_ExfiltrateData_Handler,
		},
		{
			MethodName: "NetworkScan",
			Handler:    _NetRunnersAdapter_NetworkScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netrunners.proto",
}
