// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: netrunners.proto

package netrunners

import (
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Net-Runners specific messages
type ListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // dns, https, icmp, tcp_obfuscated
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerRequest) Reset() {
	*x = ListenerRequest{}
	mi := &file_netrunners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerRequest) ProtoMessage() {}

func (x *ListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerRequest.ProtoReflect.Descriptor instead.
func (*ListenerRequest) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenerRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListenerRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ListenerRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListenerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ListenerId       string                 `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ConnectionString string                 `protobuf:"bytes,3,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListenerResponse) Reset() {
	*x = ListenerResponse{}
	mi := &file_netrunners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerResponse) ProtoMessage() {}

func (x *ListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerResponse.ProtoReflect.Descriptor instead.
func (*ListenerResponse) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{1}
}

func (x *ListenerResponse) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *ListenerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListenerResponse) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type ChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   string                 `protobuf:"bytes,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"` // dns_tunnel, http_tunnel, icmp_tunnel
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_netrunners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelRequest) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *ChannelRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ChannelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChannelRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseData  []byte                 `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_netrunners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChannelResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

func (x *ChannelResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type ExfiltrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPath      string                 `protobuf:"bytes,1,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // dns, http, icmp, https
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Encryption    map[string]string      `protobuf:"bytes,4,rep,name=encryption,proto3" json:"encryption,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExfiltrationRequest) Reset() {
	*x = ExfiltrationRequest{}
	mi := &file_netrunners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfiltrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfiltrationRequest) ProtoMessage() {}

func (x *ExfiltrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfiltrationRequest.ProtoReflect.Descriptor instead.
func (*ExfiltrationRequest) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{4}
}

func (x *ExfiltrationRequest) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

func (x *ExfiltrationRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ExfiltrationRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ExfiltrationRequest) GetEncryption() map[string]string {
	if x != nil {
		return x.Encryption
	}
	return nil
}

type ExfiltrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BytesSent      int32                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	ExfiltrationId string                 `protobuf:"bytes,3,opt,name=exfiltration_id,json=exfiltrationId,proto3" json:"exfiltration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExfiltrationResponse) Reset() {
	*x = ExfiltrationResponse{}
	mi := &file_netrunners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfiltrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfiltrationResponse) ProtoMessage() {}

func (x *ExfiltrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfiltrationResponse.ProtoReflect.Descriptor instead.
func (*ExfiltrationResponse) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{5}
}

func (x *ExfiltrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExfiltrationResponse) GetBytesSent() int32 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ExfiltrationResponse) GetExfiltrationId() string {
	if x != nil {
		return x.ExfiltrationId
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"` // stealth, full, port, service
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_netrunners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanRequest) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *ScanRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	HostsFound    int32                  `protobuf:"varint,2,opt,name=hosts_found,json=hostsFound,proto3" json:"hosts_found,omitempty"`
	PortsOpen     int32                  `protobuf:"varint,3,opt,name=ports_open,json=portsOpen,proto3" json:"ports_open,omitempty"`
	ResultsPath   string                 `protobuf:"bytes,4,opt,name=results_path,json=resultsPath,proto3" json:"results_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_netrunners_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netrunners_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_netrunners_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResponse) GetHostsFound() int32 {
	if x != nil {
		return x.HostsFound
	}
	return 0
}

func (x *ScanResponse) GetPortsOpen() int32 {
	if x != nil {
		return x.PortsOpen
	}
	return 0
}

func (x *ScanResponse) GetResultsPath() string {
	if x != nil {
		return x.ResultsPath
	}
	return ""
}

var File_netrunners_proto protoreflect.FileDescriptor

const file_netrunners_proto_rawDesc = "" +
	"\n" +
	"\x10netrunners.proto\x12\x13openclaw.netrunners\x1a\n" +
	"core.proto\"\xe2\x01\n" +
	"\x0fListenerRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12K\n" +
	"\aoptions\x18\x04 \x03(\v21.openclaw.netrunners.ListenerRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x10ListenerResponse\x12\x1f\n" +
	"\vlistener_id\x18\x01 \x01(\tR\n" +
	"listenerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\x11connection_string\x18\x03 \x01(\tR\x10connectionString\"\xe7\x01\n" +
	"\x0eChannelRequest\x12!\n" +
	"\fchannel_type\x18\x01 \x01(\tR\vchannelType\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12J\n" +
	"\aoptions\x18\x04 \x03(\v20.openclaw.netrunners.ChannelRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x0fChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_data\x18\x02 \x01(\fR\fresponseData\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\"\x85\x02\n" +
	"\x13ExfiltrationRequest\x12\x1b\n" +
	"\tdata_path\x18\x01 \x01(\tR\bdataPath\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12X\n" +
	"\n" +
	"encryption\x18\x04 \x03(\v28.openclaw.netrunners.ExfiltrationRequest.EncryptionEntryR\n" +
	"encryption\x1a=\n" +
	"\x0fEncryptionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x14ExfiltrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x05R\tbytesSent\x12'\n" +
	"\x0fexfiltration_id\x18\x03 \x01(\tR\x0eexfiltrationId\"\xc7\x01\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12G\n" +
	"\aoptions\x18\x03 \x03(\v2-.openclaw.netrunners.ScanRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\fScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x1f\n" +
	"\vhosts_found\x18\x02 \x01(\x05R\n" +
	"hostsFound\x12\x1d\n" +
	"\n" +
	"ports_open\x18\x03 \x01(\x05R\tportsOpen\x12!\n" +
	"\fresults_path\x18\x04 \x01(\tR\vresultsPath2\xe0\x04\n" +
	"\x11NetRunnersAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatus\x12\\\n" +
	"\rSetupListener\x12$.openclaw.netrunners.ListenerRequest\x1a%.openclaw.netrunners.ListenerResponse\x12Z\n" +
	"\rCovertChannel\x12#.openclaw.netrunners.ChannelRequest\x1a$.openclaw.netrunners.ChannelResponse\x12e\n" +
	"\x0eExfiltrateData\x12(.openclaw.netrunners.ExfiltrationRequest\x1a).openclaw.netrunners.ExfiltrationResponse\x12R\n" +
	"\vNetworkScan\x12 .openclaw.netrunners.ScanRequest\x1a!.openclaw.netrunners.ScanResponseB@Z>github.com/OpenClaw-Security/Stealth-Core/pkg/proto/netrunnersb\x06proto3"

var (
	file_netrunners_proto_rawDescOnce sync.Once
	file_netrunners_proto_rawDescData []byte
)

func file_netrunners_proto_rawDescGZIP() []byte {
	file_netrunners_proto_rawDescOnce.Do(func() {
		file_netrunners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_netrunners_proto_rawDesc), len(file_netrunners_proto_rawDesc)))
	})
	return file_netrunners_proto_rawDescData
}

var file_netrunners_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_netrunners_proto_goTypes = []any{
	(*ListenerRequest)(nil),        // 0: openclaw.netrunners.ListenerRequest
	(*ListenerResponse)(nil),       // 1: openclaw.netrunners.ListenerResponse
	(*ChannelRequest)(nil),         // 2: openclaw.netrunners.ChannelRequest
	(*ChannelResponse)(nil),        // 3: openclaw.netrunners.ChannelResponse
	(*ExfiltrationRequest)(nil),    // 4: openclaw.netrunners.ExfiltrationRequest
	(*ExfiltrationResponse)(nil),   // 5: openclaw.netrunners.ExfiltrationResponse
	(*ScanRequest)(nil),            // 6: openclaw.netrunners.ScanRequest
	(*ScanResponse)(nil),           // 7: openclaw.netrunners.ScanResponse
	nil,                            // 8: openclaw.netrunners.ListenerRequest.OptionsEntry
	nil,                            // 9: openclaw.netrunners.ChannelRequest.OptionsEntry
	nil,                            // 10: openclaw.netrunners.ExfiltrationRequest.EncryptionEntry
	nil,                            // 11: openclaw.netrunners.ScanRequest.OptionsEntry
	(*core.OperationRequest)(nil),  // 12: openclaw.core.OperationRequest
	(*core.Empty)(nil),             // 13: openclaw.core.Empty
	(*core.OperationResponse)(nil), // 14: openclaw.core.OperationResponse
	(*core.CapabilityList)(nil),    // 15: openclaw.core.CapabilityList
	(*core.HealthStatus)(nil),      // 16: openclaw.core.HealthStatus
}
var file_netrunners_proto_depIdxs = []int32{
	8,  // 0: openclaw.netrunners.ListenerRequest.options:type_name -> openclaw.netrunners.ListenerRequest.OptionsEntry
	9,  // 1: openclaw.netrunners.ChannelRequest.options:type_name -> openclaw.netrunners.ChannelRequest.OptionsEntry
	10, // 2: openclaw.netrunners.ExfiltrationRequest.encryption:type_name -> openclaw.netrunners.ExfiltrationRequest.EncryptionEntry
	11, // 3: openclaw.netrunners.ScanRequest.options:type_name -> openclaw.netrunners.ScanRequest.OptionsEntry
	12, // 4: openclaw.netrunners.NetRunnersAdapter.Execute:input_type -> openclaw.core.OperationRequest
	13, // 5: openclaw.netrunners.NetRunnersAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	13, // 6: openclaw.netrunners.NetRunnersAdapter.HealthCheck:input_type -> openclaw.core.Empty
	0,  // 7: openclaw.netrunners.NetRunnersAdapter.SetupListener:input_type -> openclaw.netrunners.ListenerRequest
	2,  // 8: openclaw.netrunners.NetRunnersAdapter.CovertChannel:input_type -> openclaw.netrunners.ChannelRequest
	4,  // 9: openclaw.netrunners.NetRunnersAdapter.ExfiltrateData:input_type -> openclaw.netrunners.ExfiltrationRequest
	6,  // 10: openclaw.netrunners.NetRunnersAdapter.NetworkScan:input_type -> openclaw.netrunners.ScanRequest
	14, // 11: openclaw.netrunners.NetRunnersAdapter.Execute:output_type -> openclaw.core.OperationResponse
	15, // 12: openclaw.netrunners.NetRunnersAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	16, // 13: openclaw.netrunners.NetRunnersAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	1,  // 14: openclaw.netrunners.NetRunnersAdapter.SetupListener:output_type -> openclaw.netrunners.ListenerResponse
	3,  // 15: openclaw.netrunners.NetRunnersAdapter.CovertChannel:output_type -> openclaw.netrunners.ChannelResponse
	5,  // 16: openclaw.netrunners.NetRunnersAdapter.ExfiltrateData:output_type -> openclaw.netrunners.ExfiltrationResponse
	7,  // 17: openclaw.netrunners.NetRunnersAdapter.NetworkScan:output_type -> openclaw.netrunners.ScanResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_netrunners_proto_init() }
func file_netrunners_proto_init() {
	if File_netrunners_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_netrunners_proto_rawDesc), len(file_netrunners_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_netrunners_proto_goTypes,
		DependencyIndexes: file_netrunners_proto_depIdxs,
		MessageInfos:      file_netrunners_proto_msgTypes,
	}.Build()
	File_netrunners_proto = out.File
	file_netrunners_proto_goTypes = nil
	file_netrunners_proto_depIdxs = nil
}
