// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: redteam_tools.proto

package redteam_tools

import (
	context "context"
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedteamToolsAdapter_Execute_FullMethodName                = "/openclaw.redteam_tools.RedteamToolsAdapter/Execute"
	RedteamToolsAdapter_GetCapabilities_FullMethodName        = "/openclaw.redteam_tools.RedteamToolsAdapter/GetCapabilities"
	RedteamToolsAdapter_HealthCheck_FullMethodName            = "/openclaw.redteam_tools.RedteamToolsAdapter/HealthCheck"
	RedteamToolsAdapter_EnumerateSMB_FullMethodName           = "/openclaw.redteam_tools.RedteamToolsAdapter/EnumerateSMB"
	RedteamToolsAdapter_PerformLateralMovement_FullMethodName = "/openclaw.redteam_tools.RedteamToolsAdapter/PerformLateralMovement"
	RedteamToolsAdapter_DumpCredentials_FullMethodName        = "/openclaw.redteam_tools.RedteamToolsAdapter/DumpCredentials"
	RedteamToolsAdapter_ScanVulnerabilities_FullMethodName    = "/openclaw.redteam_tools.RedteamToolsAdapter/ScanVulnerabilities"
)

// RedteamToolsAdapterClient is the client API for RedteamToolsAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Redteam Tools Adapter Service, integrates curated tools from Hexstrike-redteam
type RedteamToolsAdapterClient interface {
	Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error)
	GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error)
	HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error)
	// Redteam Tools specific functions (selected from Hexstrike-redteam)
	EnumerateSMB(ctx context.Context, in *SMBEnumerateRequest, opts ...grpc.CallOption) (*SMBEnumerateResponse, error)
	PerformLateralMovement(ctx context.Context, in *LateralMovementRequest, opts ...grpc.CallOption) (*LateralMovementResponse, error)
	DumpCredentials(ctx context.Context, in *CredentialDumpRequest, opts ...grpc.CallOption) (*CredentialDumpResponse, error)
	ScanVulnerabilities(ctx context.Context, in *VulnerabilityScanRequest, opts ...grpc.CallOption) (*VulnerabilityScanResponse, error)
}

type redteamToolsAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewRedteamToolsAdapterClient(cc grpc.ClientConnInterface) RedteamToolsAdapterClient {
	return &redteamToolsAdapterClient{cc}
}

func (c *redteamToolsAdapterClient) Execute(ctx context.Context, in *core.OperationRequest, opts ...grpc.CallOption) (*core.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.OperationResponse)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) GetCapabilities(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.CapabilityList)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) HealthCheck(ctx context.Context, in *core.Empty, opts ...grpc.CallOption) (*core.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(core.HealthStatus)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) EnumerateSMB(ctx context.Context, in *SMBEnumerateRequest, opts ...grpc.CallOption) (*SMBEnumerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SMBEnumerateResponse)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_EnumerateSMB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) PerformLateralMovement(ctx context.Context, in *LateralMovementRequest, opts ...grpc.CallOption) (*LateralMovementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LateralMovementResponse)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_PerformLateralMovement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) DumpCredentials(ctx context.Context, in *CredentialDumpRequest, opts ...grpc.CallOption) (*CredentialDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialDumpResponse)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_DumpCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redteamToolsAdapterClient) ScanVulnerabilities(ctx context.Context, in *VulnerabilityScanRequest, opts ...grpc.CallOption) (*VulnerabilityScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VulnerabilityScanResponse)
	err := c.cc.Invoke(ctx, RedteamToolsAdapter_ScanVulnerabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedteamToolsAdapterServer is the server API for RedteamToolsAdapter service.
// All implementations must embed UnimplementedRedteamToolsAdapterServer
// for forward compatibility.
//
// Redteam Tools Adapter Service, integrates curated tools from Hexstrike-redteam
type RedteamToolsAdapterServer interface {
	Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error)
	GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error)
	HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error)
	// Redteam Tools specific functions (selected from Hexstrike-redteam)
	EnumerateSMB(context.Context, *SMBEnumerateRequest) (*SMBEnumerateResponse, error)
	PerformLateralMovement(context.Context, *LateralMovementRequest) (*LateralMovementResponse, error)
	DumpCredentials(context.Context, *CredentialDumpRequest) (*CredentialDumpResponse, error)
	ScanVulnerabilities(context.Context, *VulnerabilityScanRequest) (*VulnerabilityScanResponse, error)
	mustEmbedUnimplementedRedteamToolsAdapterServer()
}

// UnimplementedRedteamToolsAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedteamToolsAdapterServer struct{}

func (UnimplementedRedteamToolsAdapterServer) Execute(context.Context, *core.OperationRequest) (*core.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) GetCapabilities(context.Context, *core.Empty) (*core.CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) HealthCheck(context.Context, *core.Empty) (*core.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) EnumerateSMB(context.Context, *SMBEnumerateRequest) (*SMBEnumerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnumerateSMB not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) PerformLateralMovement(context.Context, *LateralMovementRequest) (*LateralMovementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PerformLateralMovement not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) DumpCredentials(context.Context, *CredentialDumpRequest) (*CredentialDumpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DumpCredentials not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) ScanVulnerabilities(context.Context, *VulnerabilityScanRequest) (*VulnerabilityScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanVulnerabilities not implemented")
}
func (UnimplementedRedteamToolsAdapterServer) mustEmbedUnimplementedRedteamToolsAdapterServer() {}
func (UnimplementedRedteamToolsAdapterServer) testEmbeddedByValue()                             {}

// UnsafeRedteamToolsAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedteamToolsAdapterServer will
// result in compilation errors.
type UnsafeRedteamToolsAdapterServer interface {
	mustEmbedUnimplementedRedteamToolsAdapterServer()
}

func RegisterRedteamToolsAdapterServer(s grpc.ServiceRegistrar, srv RedteamToolsAdapterServer) {
	// If the following call panics, it indicates UnimplementedRedteamToolsAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedteamToolsAdapter_ServiceDesc, srv)
}

func _RedteamToolsAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).Execute(ctx, req.(*core.OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).GetCapabilities(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).HealthCheck(ctx, req.(*core.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_EnumerateSMB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMBEnumerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).EnumerateSMB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_EnumerateSMB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).EnumerateSMB(ctx, req.(*SMBEnumerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_PerformLateralMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LateralMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).PerformLateralMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_PerformLateralMovement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).PerformLateralMovement(ctx, req.(*LateralMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_DumpCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).DumpCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_DumpCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).DumpCredentials(ctx, req.(*CredentialDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedteamToolsAdapter_ScanVulnerabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VulnerabilityScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedteamToolsAdapterServer).ScanVulnerabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedteamToolsAdapter_ScanVulnerabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedteamToolsAdapterServer).ScanVulnerabilities(ctx, req.(*VulnerabilityScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedteamToolsAdapter_ServiceDesc is the grpc.ServiceDesc for RedteamToolsAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedteamToolsAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.redteam_tools.RedteamToolsAdapter",
	HandlerType: (*RedteamToolsAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _RedteamToolsAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _RedteamToolsAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RedteamToolsAdapter_HealthCheck_Handler,
		},
		{
			MethodName: "EnumerateSMB",
			Handler:    _RedteamToolsAdapter_EnumerateSMB_Handler,
		},
		{
			MethodName: "PerformLateralMovement",
			Handler:    _RedteamToolsAdapter_PerformLateralMovement_Handler,
		},
		{
			MethodName: "DumpCredentials",
			Handler:    _RedteamToolsAdapter_DumpCredentials_Handler,
		},
		{
			MethodName: "ScanVulnerabilities",
			Handler:    _RedteamToolsAdapter_ScanVulnerabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redteam_tools.proto",
}
