// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: redteam_tools.proto

package redteam_tools

import (
	core "github.com/OpenClaw-Security/Stealth-Core/pkg/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMBEnumerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // IP address or hostname
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMBEnumerateRequest) Reset() {
	*x = SMBEnumerateRequest{}
	mi := &file_redteam_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMBEnumerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMBEnumerateRequest) ProtoMessage() {}

func (x *SMBEnumerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMBEnumerateRequest.ProtoReflect.Descriptor instead.
func (*SMBEnumerateRequest) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{0}
}

func (x *SMBEnumerateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SMBEnumerateRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SMBEnumerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"` // Enumeration results file path
	Shares        []string               `protobuf:"bytes,3,rep,name=shares,proto3" json:"shares,omitempty"`
	Users         []string               `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMBEnumerateResponse) Reset() {
	*x = SMBEnumerateResponse{}
	mi := &file_redteam_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMBEnumerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMBEnumerateResponse) ProtoMessage() {}

func (x *SMBEnumerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMBEnumerateResponse.ProtoReflect.Descriptor instead.
func (*SMBEnumerateResponse) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{1}
}

func (x *SMBEnumerateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SMBEnumerateResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *SMBEnumerateResponse) GetShares() []string {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *SMBEnumerateResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type LateralMovementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`                              // Target host
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                              // psexec, wmi, ssh, etc.
	Credentials   string                 `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`                    // username:password or hash
	PayloadPath   string                 `protobuf:"bytes,4,opt,name=payload_path,json=payloadPath,proto3" json:"payload_path,omitempty"` // Path to the payload to execute
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LateralMovementRequest) Reset() {
	*x = LateralMovementRequest{}
	mi := &file_redteam_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LateralMovementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LateralMovementRequest) ProtoMessage() {}

func (x *LateralMovementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LateralMovementRequest.ProtoReflect.Descriptor instead.
func (*LateralMovementRequest) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{2}
}

func (x *LateralMovementRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LateralMovementRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LateralMovementRequest) GetCredentials() string {
	if x != nil {
		return x.Credentials
	}
	return ""
}

func (x *LateralMovementRequest) GetPayloadPath() string {
	if x != nil {
		return x.PayloadPath
	}
	return ""
}

func (x *LateralMovementRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type LateralMovementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // if successful session established
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LateralMovementResponse) Reset() {
	*x = LateralMovementResponse{}
	mi := &file_redteam_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LateralMovementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LateralMovementResponse) ProtoMessage() {}

func (x *LateralMovementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LateralMovementResponse.ProtoReflect.Descriptor instead.
func (*LateralMovementResponse) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{3}
}

func (x *LateralMovementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LateralMovementResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *LateralMovementResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CredentialDumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`           // Target host (if remote)
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`           // mimikatz, procdump, secretsdump
	Credentials   string                 `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"` // if remote authentication is needed
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialDumpRequest) Reset() {
	*x = CredentialDumpRequest{}
	mi := &file_redteam_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDumpRequest) ProtoMessage() {}

func (x *CredentialDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDumpRequest.ProtoReflect.Descriptor instead.
func (*CredentialDumpRequest) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialDumpRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CredentialDumpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CredentialDumpRequest) GetCredentials() string {
	if x != nil {
		return x.Credentials
	}
	return ""
}

func (x *CredentialDumpRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CredentialDumpResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DumpedCredentialsPath string                 `protobuf:"bytes,2,opt,name=dumped_credentials_path,json=dumpedCredentialsPath,proto3" json:"dumped_credentials_path,omitempty"`
	CredentialCount       int32                  `protobuf:"varint,3,opt,name=credential_count,json=credentialCount,proto3" json:"credential_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CredentialDumpResponse) Reset() {
	*x = CredentialDumpResponse{}
	mi := &file_redteam_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDumpResponse) ProtoMessage() {}

func (x *CredentialDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDumpResponse.ProtoReflect.Descriptor instead.
func (*CredentialDumpResponse) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialDumpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CredentialDumpResponse) GetDumpedCredentialsPath() string {
	if x != nil {
		return x.DumpedCredentialsPath
	}
	return ""
}

func (x *CredentialDumpResponse) GetCredentialCount() int32 {
	if x != nil {
		return x.CredentialCount
	}
	return 0
}

type VulnerabilityScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // IP address or CIDR
	Ports         []string               `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	ScanProfile   string                 `protobuf:"bytes,3,opt,name=scan_profile,json=scanProfile,proto3" json:"scan_profile,omitempty"` // e.g., "default", "full_tcp"
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VulnerabilityScanRequest) Reset() {
	*x = VulnerabilityScanRequest{}
	mi := &file_redteam_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityScanRequest) ProtoMessage() {}

func (x *VulnerabilityScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityScanRequest.ProtoReflect.Descriptor instead.
func (*VulnerabilityScanRequest) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{6}
}

func (x *VulnerabilityScanRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VulnerabilityScanRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *VulnerabilityScanRequest) GetScanProfile() string {
	if x != nil {
		return x.ScanProfile
	}
	return ""
}

func (x *VulnerabilityScanRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type VulnerabilityScanResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReportPath           string                 `protobuf:"bytes,2,opt,name=report_path,json=reportPath,proto3" json:"report_path,omitempty"`
	VulnerabilitiesFound int32                  `protobuf:"varint,3,opt,name=vulnerabilities_found,json=vulnerabilitiesFound,proto3" json:"vulnerabilities_found,omitempty"`
	DetectedServices     map[string]string      `protobuf:"bytes,4,rep,name=detected_services,json=detectedServices,proto3" json:"detected_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VulnerabilityScanResponse) Reset() {
	*x = VulnerabilityScanResponse{}
	mi := &file_redteam_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityScanResponse) ProtoMessage() {}

func (x *VulnerabilityScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redteam_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityScanResponse.ProtoReflect.Descriptor instead.
func (*VulnerabilityScanResponse) Descriptor() ([]byte, []int) {
	return file_redteam_tools_proto_rawDescGZIP(), []int{7}
}

func (x *VulnerabilityScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VulnerabilityScanResponse) GetReportPath() string {
	if x != nil {
		return x.ReportPath
	}
	return ""
}

func (x *VulnerabilityScanResponse) GetVulnerabilitiesFound() int32 {
	if x != nil {
		return x.VulnerabilitiesFound
	}
	return 0
}

func (x *VulnerabilityScanResponse) GetDetectedServices() map[string]string {
	if x != nil {
		return x.DetectedServices
	}
	return nil
}

var File_redteam_tools_proto protoreflect.FileDescriptor

const file_redteam_tools_proto_rawDesc = "" +
	"\n" +
	"\x13redteam_tools.proto\x12\x16openclaw.redteam_tools\x1a\n" +
	"core.proto\"\xbd\x01\n" +
	"\x13SMBEnumerateRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12R\n" +
	"\aoptions\x18\x02 \x03(\v28.openclaw.redteam_tools.SMBEnumerateRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x14SMBEnumerateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x16\n" +
	"\x06shares\x18\x03 \x03(\tR\x06shares\x12\x14\n" +
	"\x05users\x18\x04 \x03(\tR\x05users\"\xa0\x02\n" +
	"\x16LateralMovementRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12 \n" +
	"\vcredentials\x18\x03 \x01(\tR\vcredentials\x12!\n" +
	"\fpayload_path\x18\x04 \x01(\tR\vpayloadPath\x12U\n" +
	"\aoptions\x18\x05 \x03(\v2;.openclaw.redteam_tools.LateralMovementRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x17LateralMovementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xfb\x01\n" +
	"\x15CredentialDumpRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12 \n" +
	"\vcredentials\x18\x03 \x01(\tR\vcredentials\x12T\n" +
	"\aoptions\x18\x04 \x03(\v2:.openclaw.redteam_tools.CredentialDumpRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x16CredentialDumpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\x17dumped_credentials_path\x18\x02 \x01(\tR\x15dumpedCredentialsPath\x12)\n" +
	"\x10credential_count\x18\x03 \x01(\x05R\x0fcredentialCount\"\x80\x02\n" +
	"\x18VulnerabilityScanRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\tR\x05ports\x12!\n" +
	"\fscan_profile\x18\x03 \x01(\tR\vscanProfile\x12W\n" +
	"\aoptions\x18\x04 \x03(\v2=.openclaw.redteam_tools.VulnerabilityScanRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\x19VulnerabilityScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vreport_path\x18\x02 \x01(\tR\n" +
	"reportPath\x123\n" +
	"\x15vulnerabilities_found\x18\x03 \x01(\x05R\x14vulnerabilitiesFound\x12t\n" +
	"\x11detected_services\x18\x04 \x03(\v2G.openclaw.redteam_tools.VulnerabilityScanResponse.DetectedServicesEntryR\x10detectedServices\x1aC\n" +
	"\x15DetectedServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc1\x05\n" +
	"\x13RedteamToolsAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatus\x12i\n" +
	"\fEnumerateSMB\x12+.openclaw.redteam_tools.SMBEnumerateRequest\x1a,.openclaw.redteam_tools.SMBEnumerateResponse\x12y\n" +
	"\x16PerformLateralMovement\x12..openclaw.redteam_tools.LateralMovementRequest\x1a/.openclaw.redteam_tools.LateralMovementResponse\x12p\n" +
	"\x0fDumpCredentials\x12-.openclaw.redteam_tools.CredentialDumpRequest\x1a..openclaw.redteam_tools.CredentialDumpResponse\x12z\n" +
	"\x13ScanVulnerabilities\x120.openclaw.redteam_tools.VulnerabilityScanRequest\x1a1.openclaw.redteam_tools.VulnerabilityScanResponseBCZAgithub.com/OpenClaw-Security/Stealth-Core/pkg/proto/redteam_toolsb\x06proto3"

var (
	file_redteam_tools_proto_rawDescOnce sync.Once
	file_redteam_tools_proto_rawDescData []byte
)

func file_redteam_tools_proto_rawDescGZIP() []byte {
	file_redteam_tools_proto_rawDescOnce.Do(func() {
		file_redteam_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redteam_tools_proto_rawDesc), len(file_redteam_tools_proto_rawDesc)))
	})
	return file_redteam_tools_proto_rawDescData
}

var file_redteam_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_redteam_tools_proto_goTypes = []any{
	(*SMBEnumerateRequest)(nil),       // 0: openclaw.redteam_tools.SMBEnumerateRequest
	(*SMBEnumerateResponse)(nil),      // 1: openclaw.redteam_tools.SMBEnumerateResponse
	(*LateralMovementRequest)(nil),    // 2: openclaw.redteam_tools.LateralMovementRequest
	(*LateralMovementResponse)(nil),   // 3: openclaw.redteam_tools.LateralMovementResponse
	(*CredentialDumpRequest)(nil),     // 4: openclaw.redteam_tools.CredentialDumpRequest
	(*CredentialDumpResponse)(nil),    // 5: openclaw.redteam_tools.CredentialDumpResponse
	(*VulnerabilityScanRequest)(nil),  // 6: openclaw.redteam_tools.VulnerabilityScanRequest
	(*VulnerabilityScanResponse)(nil), // 7: openclaw.redteam_tools.VulnerabilityScanResponse
	nil,                               // 8: openclaw.redteam_tools.SMBEnumerateRequest.OptionsEntry
	nil,                               // 9: openclaw.redteam_tools.LateralMovementRequest.OptionsEntry
	nil,                               // 10: openclaw.redteam_tools.CredentialDumpRequest.OptionsEntry
	nil,                               // 11: openclaw.redteam_tools.VulnerabilityScanRequest.OptionsEntry
	nil,                               // 12: openclaw.redteam_tools.VulnerabilityScanResponse.DetectedServicesEntry
	(*core.OperationRequest)(nil),     // 13: openclaw.core.OperationRequest
	(*core.Empty)(nil),                // 14: openclaw.core.Empty
	(*core.OperationResponse)(nil),    // 15: openclaw.core.OperationResponse
	(*core.CapabilityList)(nil),       // 16: openclaw.core.CapabilityList
	(*core.HealthStatus)(nil),         // 17: openclaw.core.HealthStatus
}
var file_redteam_tools_proto_depIdxs = []int32{
	8,  // 0: openclaw.redteam_tools.SMBEnumerateRequest.options:type_name -> openclaw.redteam_tools.SMBEnumerateRequest.OptionsEntry
	9,  // 1: openclaw.redteam_tools.LateralMovementRequest.options:type_name -> openclaw.redteam_tools.LateralMovementRequest.OptionsEntry
	10, // 2: openclaw.redteam_tools.CredentialDumpRequest.options:type_name -> openclaw.redteam_tools.CredentialDumpRequest.OptionsEntry
	11, // 3: openclaw.redteam_tools.VulnerabilityScanRequest.options:type_name -> openclaw.redteam_tools.VulnerabilityScanRequest.OptionsEntry
	12, // 4: openclaw.redteam_tools.VulnerabilityScanResponse.detected_services:type_name -> openclaw.redteam_tools.VulnerabilityScanResponse.DetectedServicesEntry
	13, // 5: openclaw.redteam_tools.RedteamToolsAdapter.Execute:input_type -> openclaw.core.OperationRequest
	14, // 6: openclaw.redteam_tools.RedteamToolsAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	14, // 7: openclaw.redteam_tools.RedteamToolsAdapter.HealthCheck:input_type -> openclaw.core.Empty
	0,  // 8: openclaw.redteam_tools.RedteamToolsAdapter.EnumerateSMB:input_type -> openclaw.redteam_tools.SMBEnumerateRequest
	2,  // 9: openclaw.redteam_tools.RedteamToolsAdapter.PerformLateralMovement:input_type -> openclaw.redteam_tools.LateralMovementRequest
	4,  // 10: openclaw.redteam_tools.RedteamToolsAdapter.DumpCredentials:input_type -> openclaw.redteam_tools.CredentialDumpRequest
	6,  // 11: openclaw.redteam_tools.RedteamToolsAdapter.ScanVulnerabilities:input_type -> openclaw.redteam_tools.VulnerabilityScanRequest
	15, // 12: openclaw.redteam_tools.RedteamToolsAdapter.Execute:output_type -> openclaw.core.OperationResponse
	16, // 13: openclaw.redteam_tools.RedteamToolsAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	17, // 14: openclaw.redteam_tools.RedteamToolsAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	1,  // 15: openclaw.redteam_tools.RedteamToolsAdapter.EnumerateSMB:output_type -> openclaw.redteam_tools.SMBEnumerateResponse
	3,  // 16: openclaw.redteam_tools.RedteamToolsAdapter.PerformLateralMovement:output_type -> openclaw.redteam_tools.LateralMovementResponse
	5,  // 17: openclaw.redteam_tools.RedteamToolsAdapter.DumpCredentials:output_type -> openclaw.redteam_tools.CredentialDumpResponse
	7,  // 18: openclaw.redteam_tools.RedteamToolsAdapter.ScanVulnerabilities:output_type -> openclaw.redteam_tools.VulnerabilityScanResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_redteam_tools_proto_init() }
func file_redteam_tools_proto_init() {
	if File_redteam_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redteam_tools_proto_rawDesc), len(file_redteam_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redteam_tools_proto_goTypes,
		DependencyIndexes: file_redteam_tools_proto_depIdxs,
		MessageInfos:      file_redteam_tools_proto_msgTypes,
	}.Build()
	File_redteam_tools_proto = out.File
	file_redteam_tools_proto_goTypes = nil
	file_redteam_tools_proto_depIdxs = nil
}
