// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息定义
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *OperationRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *OperationRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Artifacts     map[string]string      `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OperationResponse) GetArtifacts() map[string]string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Operations    []*OperationRequest    `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowRequest) GetOperations() []*OperationRequest {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *WorkflowRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Response      *OperationResponse     `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WorkflowResponse) GetResponse() *OperationResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *WorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CapabilityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityList) Reset() {
	*x = CapabilityList{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityList) ProtoMessage() {}

func (x *CapabilityList) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityList.ProtoReflect.Descriptor instead.
func (*CapabilityList) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityList) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolStatus    map[string]string      `protobuf:"bytes,1,rep,name=tool_status,json=toolStatus,proto3" json:"tool_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetToolStatus() map[string]string {
	if x != nil {
		return x.ToolStatus
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\ropenclaw.core\"\xe3\x01\n" +
	"\x10OperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12C\n" +
	"\x06params\x18\x04 \x03(\v2+.openclaw.core.OperationRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12M\n" +
	"\tartifacts\x18\x04 \x03(\v2/.openclaw.core.OperationResponse.ArtifactsEntryR\tartifacts\x1a<\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x0fWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x1f.openclaw.core.OperationRequestR\n" +
	"operations\x12K\n" +
	"\tvariables\x18\x03 \x03(\v2-.openclaw.core.WorkflowRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x10WorkflowResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12<\n" +
	"\bresponse\x18\x02 \x01(\v2 .openclaw.core.OperationResponseR\bresponse\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\",\n" +
	"\x0eCapabilityList\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\"@\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\a\n" +
	"\x05Empty\"\x0f\n" +
	"\rStatusRequest\"\x9f\x01\n" +
	"\x0eStatusResponse\x12N\n" +
	"\vtool_status\x18\x01 \x03(\v2-.openclaw.core.StatusResponse.ToolStatusEntryR\n" +
	"toolStatus\x1a=\n" +
	"\x0fToolStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x85\x02\n" +
	"\fOrchestrator\x12T\n" +
	"\x0fExecuteWorkflow\x12\x1e.openclaw.core.WorkflowRequest\x1a\x1f.openclaw.core.WorkflowResponse0\x01\x12U\n" +
	"\x10ExecuteOperation\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12H\n" +
	"\tGetStatus\x12\x1c.openclaw.core.StatusRequest\x1a\x1d.openclaw.core.StatusResponse2\xe5\x01\n" +
	"\vToolAdapter\x12L\n" +
	"\aExecute\x12\x1f.openclaw.core.OperationRequest\x1a .openclaw.core.OperationResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x14.openclaw.core.Empty\x1a\x1d.openclaw.core.CapabilityList\x12@\n" +
	"\vHealthCheck\x12\x14.openclaw.core.Empty\x1a\x1b.openclaw.core.HealthStatusB:Z8github.com/OpenClaw-Security/Stealth-Core/pkg/proto/coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: openclaw.core.OperationRequest
	(*OperationResponse)(nil), // 1: openclaw.core.OperationResponse
	(*WorkflowRequest)(nil),   // 2: openclaw.core.WorkflowRequest
	(*WorkflowResponse)(nil),  // 3: openclaw.core.WorkflowResponse
	(*CapabilityList)(nil),    // 4: openclaw.core.CapabilityList
	(*HealthStatus)(nil),      // 5: openclaw.core.HealthStatus
	(*Empty)(nil),             // 6: openclaw.core.Empty
	(*StatusRequest)(nil),     // 7: openclaw.core.StatusRequest
	(*StatusResponse)(nil),    // 8: openclaw.core.StatusResponse
	nil,                       // 9: openclaw.core.OperationRequest.ParamsEntry
	nil,                       // 10: openclaw.core.OperationResponse.ArtifactsEntry
	nil,                       // 11: openclaw.core.WorkflowRequest.VariablesEntry
	nil,                       // 12: openclaw.core.StatusResponse.ToolStatusEntry
}
var file_core_proto_depIdxs = []int32{
	9,  // 0: openclaw.core.OperationRequest.params:type_name -> openclaw.core.OperationRequest.ParamsEntry
	10, // 1: openclaw.core.OperationResponse.artifacts:type_name -> openclaw.core.OperationResponse.ArtifactsEntry
	0,  // 2: openclaw.core.WorkflowRequest.operations:type_name -> openclaw.core.OperationRequest
	11, // 3: openclaw.core.WorkflowRequest.variables:type_name -> openclaw.core.WorkflowRequest.VariablesEntry
	1,  // 4: openclaw.core.WorkflowResponse.response:type_name -> openclaw.core.OperationResponse
	12, // 5: openclaw.core.StatusResponse.tool_status:type_name -> openclaw.core.StatusResponse.ToolStatusEntry
	2,  // 6: openclaw.core.Orchestrator.ExecuteWorkflow:input_type -> openclaw.core.WorkflowRequest
	0,  // 7: openclaw.core.Orchestrator.ExecuteOperation:input_type -> openclaw.core.OperationRequest
	7,  // 8: openclaw.core.Orchestrator.GetStatus:input_type -> openclaw.core.StatusRequest
	0,  // 9: openclaw.core.ToolAdapter.Execute:input_type -> openclaw.core.OperationRequest
	6,  // 10: openclaw.core.ToolAdapter.GetCapabilities:input_type -> openclaw.core.Empty
	6,  // 11: openclaw.core.ToolAdapter.HealthCheck:input_type -> openclaw.core.Empty
	3,  // 12: openclaw.core.Orchestrator.ExecuteWorkflow:output_type -> openclaw.core.WorkflowResponse
	1,  // 13: openclaw.core.Orchestrator.ExecuteOperation:output_type -> openclaw.core.OperationResponse
	8,  // 14: openclaw.core.Orchestrator.GetStatus:output_type -> openclaw.core.StatusResponse
	1,  // 15: openclaw.core.ToolAdapter.Execute:output_type -> openclaw.core.OperationResponse
	4,  // 16: openclaw.core.ToolAdapter.GetCapabilities:output_type -> openclaw.core.CapabilityList
	5,  // 17: openclaw.core.ToolAdapter.HealthCheck:output_type -> openclaw.core.HealthStatus
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
