// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_ExecuteWorkflow_FullMethodName  = "/openclaw.core.Orchestrator/ExecuteWorkflow"
	Orchestrator_ExecuteOperation_FullMethodName = "/openclaw.core.Orchestrator/ExecuteOperation"
	Orchestrator_GetStatus_FullMethodName        = "/openclaw.core.Orchestrator/GetStatus"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 核心协调服务
type OrchestratorClient interface {
	ExecuteWorkflow(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowResponse], error)
	ExecuteOperation(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) ExecuteWorkflow(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_ExecuteWorkflow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkflowRequest, WorkflowResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ExecuteWorkflowClient = grpc.ServerStreamingClient[WorkflowResponse]

func (c *orchestratorClient) ExecuteOperation(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ExecuteOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
//
// 核心协调服务
type OrchestratorServer interface {
	ExecuteWorkflow(*WorkflowRequest, grpc.ServerStreamingServer[WorkflowResponse]) error
	ExecuteOperation(context.Context, *OperationRequest) (*OperationResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) ExecuteWorkflow(*WorkflowRequest, grpc.ServerStreamingServer[WorkflowResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedOrchestratorServer) ExecuteOperation(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteOperation not implemented")
}
func (UnimplementedOrchestratorServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_ExecuteWorkflow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).ExecuteWorkflow(m, &grpc.GenericServerStream[WorkflowRequest, WorkflowResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ExecuteWorkflowServer = grpc.ServerStreamingServer[WorkflowResponse]

func _Orchestrator_ExecuteOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ExecuteOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ExecuteOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ExecuteOperation(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.core.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOperation",
			Handler:    _Orchestrator_ExecuteOperation_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Orchestrator_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteWorkflow",
			Handler:       _Orchestrator_ExecuteWorkflow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}

const (
	ToolAdapter_Execute_FullMethodName         = "/openclaw.core.ToolAdapter/Execute"
	ToolAdapter_GetCapabilities_FullMethodName = "/openclaw.core.ToolAdapter/GetCapabilities"
	ToolAdapter_HealthCheck_FullMethodName     = "/openclaw.core.ToolAdapter/HealthCheck"
)

// ToolAdapterClient is the client API for ToolAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 工具适配器必须实现的服务
type ToolAdapterClient interface {
	Execute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityList, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type toolAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewToolAdapterClient(cc grpc.ClientConnInterface) ToolAdapterClient {
	return &toolAdapterClient{cc}
}

func (c *toolAdapterClient) Execute(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, ToolAdapter_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolAdapterClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityList)
	err := c.cc.Invoke(ctx, ToolAdapter_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolAdapterClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, ToolAdapter_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolAdapterServer is the server API for ToolAdapter service.
// All implementations must embed UnimplementedToolAdapterServer
// for forward compatibility.
//
// 工具适配器必须实现的服务
type ToolAdapterServer interface {
	Execute(context.Context, *OperationRequest) (*OperationResponse, error)
	GetCapabilities(context.Context, *Empty) (*CapabilityList, error)
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedToolAdapterServer()
}

// UnimplementedToolAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolAdapterServer struct{}

func (UnimplementedToolAdapterServer) Execute(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedToolAdapterServer) GetCapabilities(context.Context, *Empty) (*CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedToolAdapterServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedToolAdapterServer) mustEmbedUnimplementedToolAdapterServer() {}
func (UnimplementedToolAdapterServer) testEmbeddedByValue()                     {}

// UnsafeToolAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolAdapterServer will
// result in compilation errors.
type UnsafeToolAdapterServer interface {
	mustEmbedUnimplementedToolAdapterServer()
}

func RegisterToolAdapterServer(s grpc.ServiceRegistrar, srv ToolAdapterServer) {
	// If the following call panics, it indicates UnimplementedToolAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolAdapter_ServiceDesc, srv)
}

func _ToolAdapter_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolAdapterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolAdapter_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolAdapterServer).Execute(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolAdapter_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolAdapterServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolAdapter_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolAdapterServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolAdapter_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolAdapterServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolAdapter_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolAdapterServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolAdapter_ServiceDesc is the grpc.ServiceDesc for ToolAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openclaw.core.ToolAdapter",
	HandlerType: (*ToolAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ToolAdapter_Execute_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _ToolAdapter_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ToolAdapter_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
